### ISSUE TITLE
[BUG] Sendo mandado pra outro local ao alterar cabelo

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#10]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

Quando entra no cabelereiro pra mudar o cabelo, é mandado pra outro local, e você não consegue ver o cabelo que tá colocando.

**Comportamento esperado**

Permanecer fisicamente no cabelereiro e poder ver as alterações. 

**Passos para reprodução**

Basta ir em um cabelereiro In Game e tentar mudar o cabelo.

**Contexto**

Quando você tá mudando o cabelo, você não consegue ver as alterações que estão sendo feitas, e quando termina de mudar, vai pro lugar da criação de personagem, como mostra nessa print: https://cdn.discordapp.com/attachments/747598463868600370/790337553291018310/unknown.png

Acho que a mudança de cabelo identifica como se fosse a criação de personagem, e você é mandado pra lá, também por isso você não consegue ver o cabelo que tá mudando (pela skin do personagem não estar ali, onde a câmera mostra.)

**Solução possível**

Colocar pra skin do personagem se manter no estabelecimento, em vez de ir pro local da criação de personagem.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.0 alpha
