### ISSUE TITLE
BlackOut

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#100]
**Descrição curta**
   Um sistema que faz apagão de luzes do servidor inteiro, da cidade inteira, para ser mais específica.

**Descrição detalhada**
   O comando seria baseado apenas para a administração, para futuros tipos de roleplay, como por exemplo, uma tempestade e faltar luz! Uma causa natural de ventaval, ou até mesmo o GOV reparar um poste e por ai vai.

**Como essa sugestão vai melhorar o servidor?**
  Adicionaria algo imersivo para fim pequenos de chuva super forte e um ROLEPLAY de vez em quando, para um futuro emprego do governo que mexe, nos postes e afiações.

**Comment by vitorvasc** [comment]
Diante da atual situação do time de desenvolvimento, que vêm trabalhando em diversos sistemas complexos e que serão utilizados por todos os jogadores diariamente, não vemos este item como algo essencial para este momento.

Não descartamos a implementação e podemos voltar a considerar esta sugestão no futuro.

**Comment by Hayran** [comment]
Esse sistema é nativo do GTA, no futuro dá para por fácil através de mudança de clima.
