### ISSUE TITLE
Contador do tempo da chamada, continua ativo.

### ISSUE THREAD

**Issue by MariannaDiabolica64** [Blaine-Life/blaine-issues#102]
Ontem fazendo role-play, liguei para um amigo. Até ai tudo bem, conversamos e desligamos, passou 2 horas de roleplay, fui até ele e etc. Voltando para casa e abrindo o celular para ver as mensagens, me deparo que a ligação tá "em continuídade" mas apenas, bug visual, pois não estava literalmente em "ligação". O contador marcou o tempo todo, após 2H de roleplay e não consegui sair dessa tela para ver as mensagens, travou nela.
https://imgur.com/a/axORuga

**Comment by cybernitsche** [comment]
não é um bug tão incomum de acontecer, o mesmo já aconteceu comigo 2 vezes https://cdn.discordapp.com/attachments/801328458801348639/801569713439113246/unknown.png

não sei como replicar, parece que quando uma chamada e feita e dura um tempo, tem uma chance aleatória de acontecer com o player caso o outro lado desligue primeiro.

**Comment by vanessa** [comment]
Controle interno: https://linear.app/blainelife/issue/GM-139/tela-de-chamada-continua-ativa-apos-chamada-ter-terminado

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
