### ISSUE TITLE
Problema no editor (menu)

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#105]
**Versão do Servidor**
`Versão v1.6.0 Open Alpha`

**Comportamento atual**
A coordenada do menu reseta depois de vários ticks.

**Comportamento esperado**

Não resetar após vários ticks.

**Passos para reprodução**

https://youtu.be/8N1P74UHCOo

**Contexto**

Apenas mover a mobília de maneira precisa.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
É comportamento padrão do NativeUI. O menu de precisão é feito pra alterar a coordenada do objeto em uma pequena range (aprox entre -10 e +10). Caso o objeto esteja resetando antes de atingir a posição desejada, recoloque-o mais próximo à posição final com algum dos outros dois modos de edição.
