### ISSUE TITLE
Adicionar congelamento temporário ao jogador que entrar em uma propriedade

### ISSUE THREAD

**Issue by Porphirio** [Blaine-Life/blaine-issues#108]
**Descrição**
Adicionar _freeze_/congelamento de **1 segundo** ao jogador que entrar em uma propriedade.

**Como essa sugestão vai melhorar o servidor?**
Resolverá o problema de loading do furniture system para que não atravesse o piso e fique preso no virtual world.

**Comment by VictorFerraresi** [comment]
Adicionado configuração no /config para escolher quantos segundos você quer ser congelado ao entrar em interiores (0 a 10s) na 1.6.1

**Comment by Porphirio** [comment]
**Melhoria**
Remover congelamento ao sair de um interior.

**Motivo**
Os problemas causados por não carregamento ocorrem apenas as mobílias do furniture system.
