### ISSUE TITLE
Test-Drive / Mundo paralelo

### ISSUE THREAD

**Issue by SeHisoka** [Blaine-Life/blaine-issues#109]
**Descrição curta**
Criar um sistema para que os jogadores consigam testar os veículos das concessionárias em um outro Virtual World ou algo similar.

**Descrição detalhada**
Os veículos do GTA V diferem em N aspectos, tendo os mais diversos tipo de velocidade, controle, tração, etc. Tendo em vista a variedade de veículos no jogo, seria interessante um sistema de test-drive que o jogador testasse o carro em um mundo diferente, bem como é inicialmente com o taxi, onde não há jogadores para que não aja problemas.

Ao chegar na concessionária, o jogador conseguiria ter acesso a compra do veículo e também ao test-drive. Se iria existir uma limitação de tempo para o jogador ficar testando, isso acho que caberia a vocês decidirem.

Inicialmente depois de testar o carro, o jogador poderia utilizar algum comando como: /sairtd -- e com isso voltaria para a concessionária.

**Como essa sugestão vai melhorar o servidor?**
Além de manter os jogadores dentro do servidor, não tendo que sair ou pesquisar no youtube para ver o carro, isso também seria interessante para que a diversidade dos carros se torne ainda maior dentro do servidor. Fora que claro, os personagens acabariam comentando entre si sobre os testes que teriam feito com X carros e isso levaria a uma sequência de roleplays.

**Comment by vanessa** [comment]
Duplicado de #79
