### ISSUE TITLE
Sem respawn quando morto em interior

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#11]
**Versão do Servidor**

`Versão v1.3.0 Alpha`

**Comportamento atual**

Quando morre dentro de uma casa e espera pra poder aceitar morte, você continua lá mesmo depois de aceitar morte, te forçando a relogar.

**Comportamento esperado**

Que fosse enviado pro hospital como acontece normalmente quando fora de interior.

**Passos para reprodução**

- Entre em um interior.
- /setarvida [seuid] 0
- Morra.
- Espera 60 segundos pra poder aceitar morte.
- /aceitar morte.
- Perpetue caído até relogar, porque nem /reviver funciona

Vídeo seguindo os passos:
https://www.youtube.com/watch?v=vuV6EwCyEc0

**Contexto**

Como este problema te afetou? Força o player a relogar quando acontece.
O que você estava tentando fazer? Testando :D

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.1 alpha
