### ISSUE TITLE
Visualização dos interiores disponíveis in-game sem a necessidade de um admin

### ISSUE THREAD

**Issue by Day-OS** [Blaine-Life/blaine-issues#112]
**Descrição curta**
Adicionar a possibilidade de ver os diversos interiores sem a necessidade de uma lista e poupando tempo de administradores.

**Descrição detalhada**
Quando vamos ao fórum pedir que mudem o interior de uma certa propriedade, é necessário que tanto o admin quanto o jogador fique online ao mesmo tempo, já que não há uma lista com todos os interiores existentes. Ao invés de gastar tempo tirando print atrás de print pra fazer uma lista, poderia simplesmente ter uma forma de ver os interiores (prontos) disponíveis com seus respectivos códigos. A pessoa iria escolher o interior que bem desejasse, o colocaria no tópico do fórum e, sem precisar que o admin e o jogador estejam presentes ao mesmo tempo, poderia simplesmente alterar o interior (como já é feito atualmente com o interior personalizado).

**Como essa sugestão vai melhorar o servidor?**
Iria facilitar o trabalho da administração, já que ela não teria que fazer mais um trabalho manual (criar a lista de interiores com fotos e tudo mais) e não teria também que mostrar um interior atrás do outro para o jogador.

**Comment by VictorFerraresi** [comment]
Os interiores foram catalogados no fórum, na área de Propriedades.
