### ISSUE TITLE
SMS do celular — Mensagens que são retornadas, não são visiveis no histórico de SMS

### ISSUE THREAD

**Issue by MariannaDiabolica64** [Blaine-Life/blaine-issues#113]
![1ad51ad](https://user-images.githubusercontent.com/77593393/105570087-ce39ce00-5d25-11eb-9b96-55b7f2715ca3.png)
As mensagens que são retornadas, não salvam no SMS/painel do celular, acabam não tendo histórico, apenas mensagens iniciais básicas.

**Comment by MariannaDiabolica64** [comment]
Relogando/entrando de novo. As mensagens surgem, demoram um pouquinho mas surge de volta... Mas no mesmo dia/hora que tá trocando o SMS, fica do mesmo jeito, só as primeiras e não dá mais histórico do que tá sendo falado no momento

**Comment by vanessa** [comment]
@MariannaDiabolica64 Não entendi. Pode colocar um vídeo reproduzindo o problema que você está reportando?

**Comment by vanessa** [comment]
@MariannaDiabolica64 por gentileza, utilize o formato que apareceu para você na hora de escrever a issue.

**Comment by MariannaDiabolica64** [comment]
> @MariannaDiabolica64 Não entendi. Pode colocar um vídeo reproduzindo o problema que você está reportando?

  Oi, não tem como gravar vídeo... É inexplicável até isso, consiste assim:
*No celular:
  Mari manda mensagem para o Fulano. E o Fulano recebeu a mensagem.

 Ambos fecham seus celulares fazem rp .  Ai mais tarde, voltam a conversar, ai que inicia o bug, o histórico de mensagem não é salvo. O que você vai estar mandando de novo para a mesma pessoa, só vai ser visivel no /chat/, histórico de mensagem no celular, não vai aparecer as mensagens. Apenas relogando para re-aparecer e atualizar.  E perdão, próximo bug report faço no formato.

**Comment by vanessa** [comment]
@MariannaDiabolica64 Isso aconteceu mais alguma vez desde que você abriu essa issue?

**Comment by MariannaDiabolica64** [comment]
Sim, sempre ocorre @vanessa .

**Comment by MariannaDiabolica64** [comment]
Sim @vanessa . Sempre ocorre, hoje mesmo ocorreu, Taylor Fuller me mandou mensagens e não aparecia no /celular nas mensagens

**Comment by vanessa** [comment]
Controle interno: https://linear.app/blainelife/issue/GM-141/mensagens-nao-aparecem-no-historico

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
