### ISSUE TITLE
/animfumar bugado

### ISSUE THREAD

**Issue by Meirinh4** [Blaine-Life/blaine-issues#114]
**Versão do Servidor**

`Versão v1.6.2`

**Comportamento atual**

Quando você ativa a animação, o personagem começa a ter uma convulsão.

**Comportamento esperado**

Era pra funcionar normalmente.

**Passos para reprodução**

Dê /animfumar (em qualquer numero), algumas não vão funcionar mas outras funcionam e acabam bugando meu jogo.

**Contexto**

Tive que relogar no servidor porque o SA não funcionou com esse anim.

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.7oa
