### ISSUE TITLE
/cargo demite funcionário

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#118]
**Versão do Servidor**

`Versão v1.6.3 Open Alpha`

**Comportamento atual**

Quando eu tento setar o cargo de um funcionário, ele é demitido.

**Comportamento esperado**

O nome do cargo mudaria, mas o funcionário é demitido.

**Passos para reprodução**

Contrate alguém via sistema de companhia. Tente mudar o cargo.

![Grand Theft Auto V Screenshot 2021 01 25 - 13 50 04 87](https://user-images.githubusercontent.com/44041139/105737347-993f9e00-5f14-11eb-9d35-9a05340dcb69.png)
![Grand Theft Auto V Screenshot 2021 01 25 - 13 50 08 20](https://user-images.githubusercontent.com/44041139/105737326-9349bd00-5f14-11eb-820a-71496120a411.png)
**Contexto**

Gostaria de setar o cargo correto dos meus funcionários.

**Solução possível**

-

**Comment by VictorFerraresi** [comment]
O uso correto do comando é:
/cargo [id do jogador] [cargo (0-3)]

O cargo é um número inteiro que vai de 0 a 3.
0 - Demitir
1 - Funcionário
2 - Gerente
3 - Dono
