### ISSUE TITLE
Carro respawnando com pouca gasolina

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#119]
**Versão do Servidor**

`Versão v1.6.3.

**Comportamento atual**

Abasteci meu carro até o tanque ficar 100% e no outro dia quando eu spawnei o carro e a gasolina caiu até a casa dos 10%. Eu não desespawnei o veiculo no primeiro dia, quando spawnei no outro dia a gasolina caiu. No segundo dia eu desespawnei e mesmo assim a gasolina caiu também.

Prints: https://imgur.com/4wvTObP = Abastecendo, isso foi ontem de noite, fizemos um rp de assaltar uma loja e depois disso escondemos o carro e não usamos novamente.
https://imgur.com/tIqjoxs = Spawnei hoje de manhã e a gasolina caiu.

**Comportamento esperado**

A gasolina permanecer a mesma de quando o carro desespawnou ou foi desligado.

**Passos para reprodução**

1 - Abastecer o carro até 100%.
2 - Desespawnar ou deixar ele em algum canto até desespawnar sozinho (GMX).

**Contexto**

Gastei uns 600 doláres pra abastecer.

**Solução possível**

N/A.

**Comment by sentinel5959** [comment]
Esqueci de colocar que o servidor caiu ontem de madrugada, talvez seja por isso. Não me recordo se na primeira vez o servidor tinha caido também.

**Comment by VictorFerraresi** [comment]
Julgo que isso esteja acontecendo quando o veículo fica spawnado, porque no /v estacionar o veículo é salvo no banco de dados imediatamente. Consegue confirmar? Caso positivo, a resposta é a mesma do #120, com uma exceção:

Estou implementando um comando para salvamento de todos os veículos antes do GMX.

**Comment by sentinel5959** [comment]
Deixei meu carro spawnado e não aconteceu nada

**Comment by VictorFerraresi** [comment]
Não consegui reproduzir, reabra o ticket caso o erro persista.
