### ISSUE TITLE
Última munição eterna, Rifles e Sub's

### ISSUE THREAD

**Issue by GabrielAparecido36** [Blaine-Life/blaine-issues#12]
**Versão do Servidor**

`Versão v1.3.0 Alpha

**Comportamento atual**

Caso você esteja com um Rifle ou Sub (Não testei com todas as armas), você tenha apenas 1 bala, gaste ela, volte a arma pro inventário e pegue a arma do inventário, você vai ter 1 bala novamente.

**Comportamento esperado**

A munição ficar zerada

**Passos para reprodução**

Tenha 1 bala no pente e gaste;
Guarde a arma no inventário;
Pegue a arma no inventário novamente.
https://youtu.be/LFBmzIP3zcU - Segue o vídeo mostrando o bug.

**Contexto**

Eu guardei a arma sem querer e voltou com 1 bala.

**Solução possível**

Provavelmente está faltando um .set para zerar a munição.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.2 open alpha
