### ISSUE TITLE
Cair dentro de um interior faz vc spawnar em outro lugar quando reconectar

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#120]
**Versão do Servidor**

`Versão v1.6.3 Open Alpha`

**Comportamento atual**

Loguei hoje de manhã e spawnei em Little Seoul sendo que eu cai dentro da casa do Earnest Keefer na Forum Drive, Strawberry.

**Comportamento esperado**

O jogador reconectar aonde ele caiu ou reconectar em sua casa.

**Passos para reprodução**

Derrubar o server estando dentro de um interior kkkk Não testei se sua internet cair sozinha ou outros métodos.

**Contexto**

Na noite anterior eu estava conectado e fazendo roleplay com o Earnest Keefer na casa dele na Forum Drive quando o servidor caiu lá pelas 2am, eu acho, e quando reconectei hoje de manhã eu spawnei em Little Seoul.

**Solução possível**

Não sei.

**Comment by VictorFerraresi** [comment]
Quando o servidor se encerra de abruptamente, não existe fluxo de desligamento. Por este motivo, alguns rollbacks podem acontecer.
