### ISSUE TITLE
/do estático

### ISSUE THREAD

**Issue by Day-OS** [Blaine-Life/blaine-issues#121]
**Descrição curta**
Uma mensagem de /do flutuante que fique por um longo tempo em um local.

**Descrição detalhada**
Um comando em que jogadores poderiam colocar mensagens em lugares para descrever um detalhe que ficaria por um longo tempo ativo. Um cartaz na parede seguido de um link, uma pichação feita por um membro de gangue, um cheiro de miasma em um local. As opções são infinitas. 
Uma falha já prevista é que poderia se tornar algo muito poluível, mas o sistema poderia ser feito de forma que combata esse problema (1 por player, destruição dos "/do"s quando o server reinicia, ou até mesmo colocando esse sistema como feature paga).

**Como essa sugestão vai melhorar o servidor?**
Enriqueceria detalhes no mapa, colocando detalhes que jogadores em outro momento de jogatina poderiam notar, mesmo o RP fonte já tendo sido encerrado.

**Comment by VictorFerraresi** [comment]
Implementado na 1.7.4
