### ISSUE TITLE
Replicar o sistema de onboarding do táxi pra quando não houverem taxistas online

### ISSUE THREAD

**Issue by Porphirio** [Blaine-Life/blaine-issues#122]
**Descrição curta**
Título autoexplicativo. Se não houver pelo menos um taxista online, um táxi (NPC) deve ser spawnado e seguir na direção do jogador que executou o comando. Ao entrar no táxi, exibir as opções pré-estabelecidas assim como no onboarding. Sistema já pronto.

**Como essa sugestão vai melhorar o servidor?**
Evita com que os jogadores desanimem caso tenham que percorrer longas distâncias a pé.

**Comment by VictorFerraresi** [comment]
O sistema de onboarding só é possível devido á alteração da dimensão do jogador durante todo o processo, além da estaticidade dos destinos.
