### ISSUE TITLE
Adicionar timeout em facções após X período de tempo

### ISSUE THREAD

**Issue by Porphirio** [Blaine-Life/blaine-issues#123]
![image](https://user-images.githubusercontent.com/65479913/106263992-def5b280-6203-11eb-961a-0bdbdb3585c1.png)

**Descrição curta**
Remover automaticamente jogadores de suas facções ao tornarem-se inativos por mais de 14 dias (sugestivo). Inclui-se os líderes da facção, dando abertura a novos interessados ativos.

**Descrição detalhada**
Em caso de ausência justificada ou situação atípica, o jogador expulso pela inatividade deverá entrar em contato com seus líderes e quando o mesmo for da liderança deverá entrar em contato com a administração.

**Como essa sugestão vai melhorar o servidor?**
Os números no "/facções" não enganariam mais e seria possível utilizá-lo como termômetro para sempre suprir as carências vitais para o funcionamento coeso desses serviços.

**Comment by VictorFerraresi** [comment]
Processos internos da Faction Team.
