### ISSUE TITLE
Trocar a textura de uma roupa já comprada e sendo usada faz ela bugar

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#125]
**Versão do Servidor**

`Versão v1.6.4 Open Alpha.`

**Comportamento atual**

Se você trocar a textura das peças de roupa que vc está usando elas bugam e desaparecem, ou ficam sem texturas (quadriculadas) ou trocam para outro modelo. Pra consertar vc precisar trocar o modelo da roupa e voltar pra a escolhida e ai ela volta ao normal.

Álbum: https://imgur.com/a/WorSb2n

**Comportamento esperado**

Não bugar se vc deseja mudar a textura da roupa.

**Passos para reprodução**

1 - Vá até uma loja de roupas.
2 - Troque a textura de qualquer peça de roupa que vc esteja utilizando.
3 - Para voltar normal, mude o "Drawable" e volte para a que vc estava utilizando.

**Contexto**

Eu tava querendo trocar a textura da minha jaqueta e ela acabou desaparecendo. Não atrapalhou em nada pq é só vc mudar o "Drawable" e voltar para a roupa que vc escolheu e mudar a textura mas é um bugzinho chato.

**Solução possível**

N/A.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.8oa
