### ISSUE TITLE
/sairfaccao

### ISSUE THREAD

**Issue by dggDiego** [Blaine-Life/blaine-issues#126]
**Versão do Servidor**

`Versão vX.X.X X`

**Comportamento atual**

/sairfaccao não funciona.

**Comportamento esperado**

deveria sair da faccção

**Passos para reprodução**

só estar numa facção e tentar sair

**Contexto**

não consigo sair da facção

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Não era bug, o comando nunca existiu e nunca foi exibido em nenhum comando de ajuda, implementado na 1.6.5
