### ISSUE TITLE
911 discado no telefone diz que não existe

### ISSUE THREAD

**Issue by matheussbdo** [Blaine-Life/blaine-issues#128]
**Versão do Servidor**

`Versão v1.6.4

**Comportamento atual**

Quando você disca o 911 através da interface do telefone ele diz que não existe.

**Comportamento esperado**

911 funcionar sendo discado através da interface do telefone.

**Passos para reprodução**

Escreva aqui...

**Contexto**

Escreva aqui...

**Solução possível**

Escreva aqui...

**Comment by vanessa** [comment]
@matheussbdo estamos cientes. Por enquanto utilize `/ligar 911`.

**Comment by vanessa** [comment]
Para controle interno: https://linear.app/blainelife/issue/GM-137/ligar-para-emergencia-911

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
