### ISSUE TITLE
Mais slots de roupas na loja de roupas

### ISSUE THREAD

**Issue by NatickNtk** [Blaine-Life/blaine-issues#129]
**Descrição curta**
Título auto-explicativo, colocar mais slots de outfits de roupas disponível na loja de roupas, assim, vc pode ter um look de frio, um look pro calor, um uniforme, um look de assaltante, e por ai vai...

**Como essa sugestão vai melhorar o servidor?**
Praticidade! Não vamos ter que ficar indo na loja de roupas, gravando números de roupas, toda hora, a gente vai escolher outfits para cada situação e trocar de roupa na nossa casa.

**Comment by VictorFerraresi** [comment]
Slots extras de roupas serão liberados em breve como benefício de doadores.
