### ISSUE TITLE
Roupa em outro slot não está sendo salva entre logins

### ISSUE THREAD

**Issue by vanessa** [Blaine-Life/blaine-issues#13]
**Versão do Servidor**

`Versão v1.3.1 Open Alpha`

**Comportamento atual**

Eu comprei uma roupa pra o slot 1 e quando reloguei eu estava com a roupa padrão do GTA. Tive que ir numa loja e digitar `/roupas` para selecionar meu slot.

**Comportamento esperado**

Já que eu comprei a roupa pra o slot 1, eu esperava que esse fosse ser o slot salvo até que eu trocasse manualmente pelo menu de `/roupas`.

**Passos para reprodução**

1. Compre uma roupa para um slot != 0
2. Você estará com a roupa
3. Relogue
4. Você estará com a roupa padrão

**Contexto**

N/A

**Solução possível**

N/A

**Comment by VictorFerraresi** [comment]
@vanessa, não consegui reproduzir. Vc deu F8 reconnect com o servidor aberto, ou você deu CTRL+C e matou o servidor antes de deslogar?

**Comment by vanessa** [comment]
É verdade. Quando dei `reconnect` funcionou. Não tava salvando por causa do CTRL + C. Vou fechar.
