### ISSUE TITLE
Ao /aceitarmorte com uma pistola ela não some do seu menu de armas e dá pra para usa-la novamente mesmo depois de ter morrido.

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#130]
**Versão do Servidor**

`Versão v1.6.6 Open Alpha`

**Comportamento atual**

Quando você morre com uma pistola equipada e aceita morte, ela ainda fica no seu menu de armas mas fica desmuniciada e não aparece no /inv. Mas se você da /usar num carregador cheio, ele carrega a pistola e dá pra usa-lá novamente mas não aparece no /inv.

Arma na minha mão: https://imgur.com/OWOQUsT
Arma no menu de armas: https://imgur.com/fwoFkHp
Utilizei um carregador para a arma para testar (Desejo refundo desse carregador usado para testar o bug): https://imgur.com/ATjKxKU
Arma carregada e pronta pra maldade: https://imgur.com/Vk62xIx

**Comportamento esperado**

Ao morrer armado a arma deveria desaparecer.

**Passos para reprodução**

1 - Pegue uma pistola e morra.
2 - Depois respawne. Se tudo der certo, a arma vai estar no seu menu de armas mas desmuniciada.
3 - Tente por um carregador nela.

**Contexto**

Morri numa troca de tiros contra um cavaleiro branco defensor de prostitutas e respawnei, quando respawnei a arma ainda estava no menu de armas mas desmuniciada e então fui em casa para testar se dava para usa-la novamente. Coloquei um carregador extra que eu tinha em casa e funcionou.

**Solução possível**

**Comment by VictorFerraresi** [comment]
Você morreu e deu /aceitarmorte? Você foi finalizado? To tentando reproduzir aqui mas ainda não consegui, todas as vezes ela sumiu.

**Comment by sentinel5959** [comment]
Sim, morri e dei /aceitarmorte

**Comment by sentinel5959** [comment]
Aconteceu novamente, morri numa troca de tiros e dei /aceitarmorte e arma continuou na minha roda de armas com a mesma quantidade de munições que eu tinha antes de morrer.
https://imgur.com/Vk9tJ6x

Esqueci de responder que quando vc reloga a arma some.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.9oa. Entre em contato comigo ingame pro reembolso.
