### ISSUE TITLE
Remover tranca de motocicletas

### ISSUE THREAD

**Issue by Porphirio** [Blaine-Life/blaine-issues#131]
**Descrição**
Remover a opção de trancar motocicletas.

**Como essa sugestão vai melhorar o servidor?**
Qualquer um pode montar numa moto estacionada na rua, porém precisará da chave para destravar o guidão e tirá-la do lugar.

**Comment by vitorvasc** [comment]
Seria implementado. No entanto o time de desenvolvimento concluiu que as motos podem possuem travas de guidão ou outros meios para que seja travada em seu local de estacionamento. 

Cabe aos usuários realizarem a interpretação destes pontos.
