### ISSUE TITLE
Marcação no forum

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#135]
**Descrição curta**
ser possível marcar um player no forum com @(nick do forum), e enviar uma notificação a pessoa marcada.

**Descrição detalhada**
--

**Como essa sugestão vai melhorar o servidor?**
só uma simples forma de interação entre player no forum.

**Comment by vitorvasc** [comment]
Implementado por @vanessa na última grande atualização do fórum.
