### ISSUE TITLE
Edição de animação em certos locais/certas animações

### ISSUE THREAD

**Issue by thug-thug** [Blaine-Life/blaine-issues#136]
**Descrição curta**

Estamos com problemas de animações em locais específicos, para isso, um /editarposicao ou /editaranimacao poderia vim acalhar e resolver todo o problema de maneira rápida e eficaz.

**Descrição detalhada**

A base disso funcionaria assim: Você utiliza o /sentar próximo de um objeto mas não senta perfeitamente nele, nisso, o player em seguida recebe uma notificação ou não (isso vai da staff) que ele pode editar a posição da animação com o comando /editarposanim (por exemplo), após ele digitar o comando aparece como se fosse mobiliar um móvel, porém, é o personagem que vai ser editado, podendo se levado tanto para cima como para baixo, esquerda ou direita, com intuito de ajustar a posição do personagem naquele objeto.

Seria interessante também restringir esse comando a animações que necessitam disso, desse ajuste, porque acredito que outras animações as vezes nem precisa. Também limitar o raio de edição para que não haja abuso de bugs. Minha opinião pessoal.

**Como essa sugestão vai melhorar o servidor?**

De uma forma geral, todos poderiam editar animações em qualquer tipo de objeto ou IPL de uma forma geral.

**Comment by VictorFerraresi** [comment]
Implementada na 1.8.0oa
