### ISSUE TITLE
Posição/dimensão dos jogadores buga no /ir e /trazer

### ISSUE THREAD

**Issue by Meirinh4** [Blaine-Life/blaine-issues#137]
**Versão do Servidor**

`Versão v1.6.7`

**Comportamento atual**

Em determinados momentos — não sei em que situações isso acontece, é de repente — a posição do personagem fica bugada e é impossível puxá-lo, isso quando ele entra em algum interior e tento puxá-lo para uma posição normal. Acredito que seja algo relacionado com interior e o comando /trazer, porque ele friza o personagem e não consigo puxá-lo.

**Comportamento esperado**

Eu deveria conseguir puxar o cara para todos os lados, sem ele congelar.

**Passos para reprodução**

https://www.youtube.com/watch?v=nMcdpd644sA

**Contexto**

A maioria dos jogadores que me contataram via SOS tiveram que relogar por esse erro e me senti totalmente lesado por não ter conseguido puxá-los. Eles foram obrigados a relogar.

**Solução possível**

**Comment by fmd00** [comment]
Corrigido no próximo patch.
