### ISSUE TITLE
OCELOT ARDENT SEM /JANELA

### ISSUE THREAD

**Issue by SeHisoka** [Blaine-Life/blaine-issues#138]
**Versão do Servidor**

`Versão v1.6.7`

**Comportamento atual**

O carro Ocelot Ardent por mais que tenha janela, quando tenta digitar /janela, diz que este não tem.

**Comportamento esperado**

Conseguir usar o /janela e ter [janelas fechadas] no veiculo.

**Passos para reprodução**

É só comprar um Ocelot Ardent e digitar /janela.

**Contexto**

Por não ter janelas no jogo, todo mundo escuta a conversa dentro do veiculo, mesmo estando fora.

**Solução possível**

É só identificar o veiculo pra ter janela, creio eu

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.8
