### ISSUE TITLE
Concessionárias

### ISSUE THREAD

**Issue by Eshang398** [Blaine-Life/blaine-issues#14]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
O ícone de todas as concessionárias estão iguais.

**Comportamento esperado**
O ícone deveria diferir o tipo de veículo que é comercializado na respectiva empresa: um ícone de barco para barcos, um ícone de carro para carros e assim sucessivamente.

**Passos para reprodução**
Simplesmente conferir as diversas concessionárias ao redor do mapa.

**Contexto**
Esse problema confunde novos jogadores e até mesmo os mais experientes, causando viagens desnecessárias e especialmente exaustivas para quem não possui um veículo, por exemplo. O mapa do GTA V é enorme e, nesse sentido, quanto mais pudermos dinamizar tudo, melhor.

**Solução possível**
Substituir o ícone da empresa por um condizente com o que é comercializado.

**Comment by VictorFerraresi** [comment]
Implementado na 1.6.9oa.
