### ISSUE TITLE
Bug - Insufilm

### ISSUE THREAD

**Issue by silvacvinicius** [Blaine-Life/blaine-issues#144]
Logo após o GMX, entrei no servidor para já comprar algumas peças para minha oficina e deixar algumas no estoque para iniciar os trabalhos no dia de amanhã.

Enquanto voltava para minha oficina (estava dirigindo um guincho), o admin Nego me viu IC e seguiu meu guincho até minha oficina. Quando cheguei na mesma ele pediu para eu aplicar Insufilm no carro dele e colocar um jogo de rodas.

Fizemos todo o procedimento, as rodas salvaram normalmente, porém o insufilm acabou não salvando, o próprio Nego estacionou o veículo e spawnou de novo e nada da peça salvar, nisso eu acabei perdendo uma 1x Insufilm. 

Eu comprei um outro insufilm e tentamos colocar novamente, nesse caso não deu certo. Porém prosseguimos com o RP e ele me pagou um dos insufilms e o jogo de roda normalmente.

Por favor, vejam a foto abaixo: Nisso ele já tinha instalado as peças, pois estava com sono e ia sair pra dormir. Dá pra notar que só tem a roda modificada e o vidro do carro está como padrão de fábrica.

![Grand Theft Auto V Screenshot 2021 02 11 - 02 33 55 59](https://user-images.githubusercontent.com/69477519/107606617-67694f80-6c15-11eb-85d4-822d92ade8f1.png)

Aproveito pra perguntar também: Se possível, podem reembolsar o Insufilm perdido? 

Grato.

**Comment by VictorFerraresi** [comment]
Issue fora do formato e duplicada de #145
