### ISSUE TITLE
Bug Insulfilm 

### ISSUE THREAD

**Issue by KellerM-13** [Blaine-Life/blaine-issues#145]
**Versão do Servidor**

`Versão v1.6.8 Open Alpha`

**Comportamento atual**

Após lançar o sistema de tunning eu fui instalar algumas modificações no meu veículo. Porém no momento de instalar o insulfilm o preview aparece escurecendo o vidro mas quando confirma não salva a modificação. Fica apacerendo que está sem no menu da compra. Mesmo estacionando e spawnando o veículo a peça não salvou, e eu não tive problemas em salvar as outras. Fiz o teste novamente para ver se foi algum erro meu porém também não deu certo e nessa brincadeira eu acabei perdendo 2 insulfilm. 

**Comportamento esperado**

Ao confirmar a compra da modificação o insulfilm deveria salvar nos vidros do veículo.

**Passos para reprodução**
 https://cdn.discordapp.com/attachments/574818838709796875/809327038266998784/unknown.png
https://cdn.discordapp.com/attachments/574818838709796875/809328296558329876/unknown.png

**Contexto**

Estava tentando adicionar insulfilm nos vidros do veículo.

**Solução possível**

Corrigir para que ao confirmar a compra da modificação, a alteração fique salva no veículo.

**Comment by VictorFerraresi** [comment]
Corrigido e online.
