### ISSUE TITLE
Cartela de Cigarros receta para 10 após relogar no servidor ou ter GMX

### ISSUE THREAD

**Issue by Mad-zi** [Blaine-Life/blaine-issues#146]
**Versão do Servidor**

`Versão v1.6.8 Aplha`

**Comportamento atual**
Pequeno bug na cartela de cigarros, ela vem com 10, certo? então ao usar seja quantos for, ela vai descendo para 9,8 por ai fora, porem ao relogar no servidor ela sempre vem com 10 cigarros

**Comportamento esperado**
Ao ser usada, ir gastando, até acabar e ser destruída ou ser lixo, com 0 cigarro

**Passos para reprodução**
Simples, usa a cartela, vai gastar um cigarro, ai reloga e vai ver que tem 10 novamente lá.

**Contexto**
Não tem grande prejudicação, só reparei que era um bug, decidi reportar, é algo não tão essencial de momento

**Comment by cybernitsche** [comment]
Não é necessário um GMX, é só relogar, e também acontece com garrafas de bebida.

**Comment by VictorFerraresi** [comment]
Duplicado de #81
