### ISSUE TITLE
Aumentar range do /sair

### ISSUE THREAD

**Issue by Meirinh4** [Blaine-Life/blaine-issues#147]
**Descrição curta**
Aumentar range do /sair.

**Descrição detalhada**
Acho que o título e a descrição acima já diz tudo.

**Como essa sugestão vai melhorar o servidor?**
Não ter que ficar procurando pelo lugar exato da saída, fiquei uns 20 seg procurando o lugar que tem a saída, mesmo perto da porta, acredite.

**Comment by VictorFerraresi** [comment]
A range das portas já foi alterada em updates anteriores.
