### ISSUE TITLE
Bug na animação de digitar do celular

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#149]
**Versão do Servidor**

`Versão v1.6.8 Open Alpha`

**Comportamento atual**
Quando o personagem vai fazer a animação de digitar no celular, em vez de fazer a animação normal como fazia antes de usar as duas mãos pra digitar, uma fica mexendo no outro celular do jeito padrão, e a outra fica "teclando" no ar.

**Comportamento esperado**
O personagem usar as duas mãos pra digitar como era antes.

**Passos para reprodução**
-Abra o celular
-Abra um chat
-aperte na barra de digitação e espere a animação:
<img src="https://cdn.discordapp.com/attachments/696932809104818267/809535027645644860/unknown.png" alt="Bug" width="572" height="507">

**Contexto**
<!--- Como este problema te afetou? O que você estava tentando fazer?
Não afetou, mas também não tá como deveria ser.

**Solução possível**
Just fix.

**Comment by MariannaDiabolica64** [comment]
Eu notei isso também no mesmo dia, apenas só a mão que não segura que está "escrevendo".

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
