### ISSUE TITLE
Onboarding - Alta

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#15]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**

Selecionei pra ele me deixar no bairro de Alta, e o taxista me deixou em Hawick

**Comportamento esperado**

Me deixou em frente a uma loja da Sub Urban ainda trancada por cima

**Passos para reprodução**

Não

**Contexto**

Mudar Alta para Hawick

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
