### ISSUE TITLE
Comando de despachante do LSFD envia uma mensagem com a frequência incorreta

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#154]
**Versão do Servidor**
`Versão v1.6.8-alpha`

**Comportamento atual**
O comando `/hq` do LSFD envia uma mensagem na frequência 912, mas a mensagem diz ser frequência 910.

**Comportamento esperado**
A mensagem deveria dizer que a frequência é 912.

**Passos para reprodução**
- Entre na facção 2 com cargo de liderança.
- Sintoanize na frequência 912.
- Use o comando /hq.

**Contexto**
N/A.

**Solução possível**
No comando de hq, alterar a mensagem de `*[CH: 910] Dispatch: ${string}` para `*[CH: 912] Dispatch: ${string}`.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.9oa
