### ISSUE TITLE
O machado disponível no armário do LSFD não pode ser adquirido

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#155]
**Versão do Servidor**
`Versão v1.6.8oa`

**Comportamento atual**
Ao tentar pegar o machado disponível no armário, a arma não aparece na roda de armas.

**Comportamento esperado**
O machado aparece na roda de armas.

**Passos para reprodução**
- Use o comando `/armario` quando membro do LSFD.
- Vá para os equipamentos.
- Selecione o machado.

**Contexto**
N/A.

**Solução possível**
N/A.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.9oa
