### ISSUE TITLE
Alterações na forma de cumprir uma pena no servidor (administrativa ou roleplayed)

### ISSUE THREAD

**Issue by thug-thug** [Blaine-Life/blaine-issues#157]
**Descrição curta**

_Alterar a forma que cumprimos as penas no servidor. Quando você é preso, você tem que cumprir toda sua pena online até zerar o contador, essa sugestão vem para alterar esse sistema antigo fundado no sa-mp._

**Descrição detalhada**

_Eu vou trazer algumas questões que eu viso para essa sugestão e depois trago a forma de aplicação:
Eu também não tenho total certeza dos dados que vou apresentar, mas estou usando uma base de conhecimento.
Perdoem o erros de português.

Atualmente no servidor ou em outros servidores que já jogamos, você vai preso e tem que cumprir toda sua pena online. Antigamente isso funcionava bem, a comunidade em si era mais nova, o GTA San Andreas ainda estava em alta e novos players adolescentes chegavam cada vez mais, então, um rapaz novo que não tem muito compromisso claramente consegue cumprir sua pena online. Com o passar dos tempos a comunidade amadureceu, nossa comunidade ela não se expande muito, não tem novos jogadores iniciando todos os dias no roleplay em texto, então os que eram novos foram amadurecendo e hoje muitos não tem o tempo de antes. Esse é um dos pontos.

O segundo ponto é que, isso aqui é um servidor que precisa se manter sustentável. O servidor precisa se manter tanto no roleplay como financeiramente, e um player a menos (afk preso) vai contra isso. Não podemos só se basear na questão de realismo, existe uma diferença entre fazer um servidor realista e um servidor roleplay, não dá pra ser realístico ao pé da letra porque você tira a diversão, e é isso que o servidor precisa ter.
Os tempos mudaram muito, nada é como antes, hoje em dia o jogo precisa ser prático ou você desiste de jogar, pelo menos a grande maioria, players como eu e outros que veem de 2011 mostra como nossa comunidade é, e de fato a praticidade hoje em dia tá sendo um dos maiores requisitos pra se ter em um jogo ou server.
Então a sugestão é a seguinte:
Criar uma forma para o player pagar sua pena tanto online como offline.
Eu pessoalmente sugiro assim:

Punições administrativa: Dependendo da gravidade é só pagável online, você precisa ficar online dependendo da gravidade, para pagar toda sua pena. (Acho aqui um ponto muito sério, as regras precisam ser preservadas e evitar que todo mundo ache fácil cometer uma infração e pagar por ela).
Punições leve você paga 25% offline e 75% online.

Prisões pelas facções governamentais:
Você pode cumprir sua pena 75% offline e 25% online.
 
Hoje em dia no servidor não é regra você ter que cumprir sua pena fazendo roleplay de preso, então, um player preso é um player afk(offline).
 Deixar um player pagando sua pena ic, somente online, morfando na cadeia, é desnecessário, cansativo e inviável. Estamos tirando um jogador do roleplay para ele ser um AFK preso.
Então se o cara vai ficar afk de todo jeito, porque ele não pode cumprir uns 75% da pena offline? Não mudaria nada, praticamente nada, somente em quantos players há logado no servidor. E os 25% de sua pena serve para ele pagar online, uma forma de se ele quiser, ele pode fazer roleplay dentro do presídio nesses seus 25%. Quanto mais incluirmos os jogadores em roleplays mais teremos um servidor vivo disso, ou infelizmente vamos se tornar um “interpretação avançada com mais de cem players e nenhum nas ruas”
Eu também não acho que os tempos de prisões deve mudar, os tempos estão bons no meu ponto de vista e com esse sistema se torna mais prático para o player.
Eu só queria uma atenção redobrada aos admins sobre o rp-fear e analisar como isso iria afeta-lo._

**Como essa sugestão vai melhorar o servidor?**

Praticamente deixar o servidor vivo em roleplay, a meta e sempre vou trabalhar nisso, é tirar antigas conformidades do sa-mp que exclui um player de roleplay e fazer com que aqui, no gta 5 seja diferente.

**Comment by VictorFerraresi** [comment]
A cadeia administrativa foi implementada na 1.8.1oa e têm como intuito o cumprimento da punição integralmente online. Para punições offline temporárias, o /tempban deverá ser utilizado.

**Comment by thug-thug** [comment]
As prisões ICly o usuário consegue cumprir elas offline ou precisam estar integralmente online?
