### ISSUE TITLE
A utilização da função de voz para transmissões

### ISSUE THREAD

**Issue by Hayran** [Blaine-Life/blaine-issues#159]
**Descrição curta**
Funciona que nem a função /boombox e /xmradio, só que com sistema de voz.

**Descrição detalhada**
Para trabalhar com playlist própria facilitaria muito um sistema que utiliza o sistema de voz do game para transmitir, a utilização seria igual a /xmradio (no veículo) ou /boombox (com objeto), talvez um /dj (tendo um instrumento).

**Como essa sugestão vai melhorar o servidor?**

Seria legal, pois neste canal, transmitir por conta própria, diretamente, fica melhor pois dá mais qualidade e evita bugs de algumas .mp3 não funcionar nas /boombox e /xmradio (enquanto esses .mp3 estão bons). É uma alternativa de canal bem melhor para transmitir no final e desenvolveria melhor os RP de colocar música, dj etc.

**Comment by vitorvasc** [comment]
Não vemos isto como um sistema sendo implementado no servidor - ao menos no atual momento. O que muitos jogadores utilizam como alternativa é a criação de um streaming de áudio gratuito (exemplo: http://www.listen2myradio.com/) e softwares próprios para transmissão de rádios web.

A utilização dos itens mencionados acima permite que você crie um link de transmissão gratuito e utilize sua própria voz/playlists durante a transmissão, que poderá ser adicionada dentro do jogo.

Caso necessário, podemos conversar com os jogadores que utilizam estas alternativas para a criação de um tutorial no fórum.

**Comment by Hayran** [comment]
Antes o sistema de xmradio não funcionava todos os tipos do MP3 incluindo da listen2myradio, depois da atualização começou a pegar.
