### ISSUE TITLE
Ícones de Departamentos

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#16]
**Versão do Servidor**

`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Remover todos os ícones dos Departamentos do LSPD/LSFD pelo mapa que não são usados.

**Comportamento esperado**
Deixar apenas os ícones dos Departamentos que serão usados pelas duas facções.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Implementado com o novo sistema de blips de propriedades.
