### ISSUE TITLE
Mensagens do ATM não aparecem no chat

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#162]
**Versão do Servidor**
`Versão v1.6.8oa`

**Comportamento atual**
Mesmo com a configuração marcada para exibir informações no chat, a informação de "saque" do ATM aparece na tela.

**Comportamento esperado**
A mensagem de sucesso do saque aparece no chat.

**Passos para reprodução**
- Pelo `/config` altere a configuração de exibição de mensagens informativas para o chat.
- Use um ATM e saque dinheiro.

**Contexto**
N/A.

**Solução possível**
Colocar a verificação no sistema de ATM para que se o player tiver configurado para exibir mensagens no chat, exibir no chat ao invés da tela.

**Comment by VictorFerraresi** [comment]
É comportamento esperado, o chat não deveria aparecer quando o ATM está aberto, por esse motivo, a notificação é forçada (ela aparece mesmo se o chat estiver fechado).
