### ISSUE TITLE
Não é possível re-equipar as armas no /armario ao perdê-las

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#163]
**Versão do Servidor**
`Versão v1.6.8oa`

**Comportamento atual**
Ao perder as suas armas da facção (seja por ter morrido ou por ter perdido-as usando `/trabalho`) não é possível equipá-las novamente sem antes selecionar a opção de "remover equipamentos".

**Comportamento esperado**
As armas podem ser equipadas normalmente.

**Passos para reprodução**
- Entre em serviço usando o `/trabalho`.
- Pegue pelo menos uma arma no `/armario`.
- Saia de serviço usando o `/trabalho` ou;
- Fique inconsciente para que perca suas armas.
- Tente equipar as armas novamente pelo armário.

**Contexto**
N/A.

**Solução possível**
Verificar se o player possui determinada arma na roda de armas dele ao invés de verificar usando as informações do jogador armazenadas pelo servidor, ou fazer com que as armas sejam removidas das informações do player ao morrer/sair de serviço e não só da roda de armas.

**Comment by VictorFerraresi** [comment]
Corrigido previamente na 1.7.1
