### ISSUE TITLE
bug no f7 para remover o HUD após usar /config

### ISSUE THREAD

**Issue by Mad-zi** [Blaine-Life/blaine-issues#165]
**Versão do Servidor**
`Versão v1.6.9 Alpha`

**Comportamento atual**
Usando o f7 normalmente, ele remove, chat, mapa, dinheiro e nome dos jogadores, após fazer /config o nome dos jogadores não desaparece quando se clica no f7.

**Comportamento esperado**
Desaparecer o nome dos jogadores, mapa, chat e dinheiro após clicar no f7

**Passos para reprodução**

- Inicialmente dar /config, não é necessário alterar nada, apenas dê "SALVAR"
- Pode observar que ao clicar no f7 o nome dos jogadores continua a aparecer.

**Contexto**
Devido a necessidade de tirar prints para edição de RP, é necessário relogar para as print's ficarem todas dentro do contexto das restantes prints

**Solução possível**
--

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.2
