### ISSUE TITLE
Liveries das ambulâncias do LSFD são randomizadas

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#166]
**Versão do Servidor**
`Versão v1.6.9oa`

**Comportamento atual**
A livery das ambulâncias do LSFD são randômicas e não são sincronizadas entre os clientes.

**Comportamento esperado**
A livery das ambulâncias são estáticas e sincronizadas.

**Passos para reprodução**
- Vá até próximo suficiente de uma ambulância para que ela carregue.
- Distancie-se da ambulância até que o mapa e o veículo seja descarregado.
- Retorne.

**Contexto**
N/A.

**Solução possível**
N/A.

**Comment by VictorFerraresi** [comment]
Aparentemente o bug era de uma ambulância específica (F381SID). Corrigi no banco de dados, deve surtir efeito no próximo GMX.
