### ISSUE TITLE
Não é possível desequipar bebidas

### ISSUE THREAD

**Issue by VinDotRun** [Blaine-Life/blaine-issues#167]
**Versão do Servidor**
`Versão v1.6.9oa`

**Comportamento atual**
Ao desequipar uma cerveja, você continua bebendo ela mas o item fica invisível e o item não é consumido, resultando em um loop infinito de animação de beber a cada vez que LMB é pressionado. Ao re-equipar o item, a garrafa aparece e você não consegue mais beber da garrafa. O item fica preso na sua mão sem a possibilidade de consumir, e ao guardar, você volta a ser capaz de pressionar LMB para beber, mas o item não é consumido.

**Comportamento esperado**
A cerveja é desequipada e você consegue bater usando LMB normalmente, e o item volta a ser consumido ao ser re-equipado.

**Passos para reprodução**
- Equipe uma cerveja usando `/usar`.
- Pressione o botão direito do mouse para desequipar o item.
- Pressione o botão esquerdo do mouse, observe que a animação de beber é executada.
- Observe no inventário que o item não é consumido mesmo com a animação sendo executada através da etapa anterior.
- Equipe novamente a cerveja.
- Tente consumir o item com o botão esquerdo. O item não é consumido novamente e a animação não é executada. O item fica preso na sua mão até que seja desequipado, e então o ciclo começa novamente como exposto na terceira etapa.

**Contexto**
Fui entrar em briga corporal e não conseguia desequipar o item. Apertei o botão direito para mirar e isso aconteceu.

**Solução possível**
N/A.

**Comment by fmd00** [comment]
Corrigido no próximo patch.
