### ISSUE TITLE
Desligar uma ligação no celular pelo botão da interface não funciona, só pelo comando /ddes

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#169]
**Versão do Servidor**

`Versão v1.7.0`

**Comportamento atual**

Se vc atender uma ligação no celular e desligar pela interface clicando naquele ícone na tela, a ligação não desliga, o celular é guardado mas ainda aparece que vc tá em ligação e vc tem que dar /desligar pra desligar.

**Comportamento esperado**

Desligar quando clicar ali.

**Passos para reprodução**

Ligue pra alguém e desligue clicando na interface.

**Contexto**

Tava em ligação com um amigo da fac e percebi esse bug.

**Solução possível**

n/a

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
