### ISSUE TITLE
Lista de jogadores (Tecla P)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#17]
**Versão do Servidor**

`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Quando você ativa a lista de jogadores, a barra preta está desproporcional com a barra branca. A experiência está sendo exibida no extremo canto direito ao invés de estar centralizado com o menu de "experiência" pertencente a barra preta.

**Comportamento esperado**
Estar tudo centralizado.

**Passos para reprodução**
https://prnt.sc/wghch2

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Essa interface será redesenhada em breve.
