### ISSUE TITLE
Adição de Aliases no comando de celular.

### ISSUE THREAD

**Issue by IketaniPG** [Blaine-Life/blaine-issues#170]
**Descrição curta**
Adicionar os comandos /cel e /celular para abrirem o celular.

**Descrição detalhada**
Adicionar os comandos /cel e /celular como aliases do atual /c, abrindo o celular por eles também.

**Como essa sugestão vai melhorar o servidor?**
Muitos jogadores estão acostumados com o /cel e /celular de outros servidores e mesmo com horas de jogatina no Blaine acabam escrevendo no automático, seria uma melhoria.

**Comment by vitorvasc** [comment]
Implementado.
