### ISSUE TITLE
As novas animações estão com o comando errado

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#173]
**Versão do Servidor**

`Versão v1.7.1 Open Alpha`

**Comportamento atual**

Alguns dos novos animes não estão funcionando e aparecem um comando diferente, exemplo: /varrer aparece no chat /tocarguitarra2 e /martelar tbm e aparece 4 exemplos do comando ao invés de 3.

Prints: https://imgur.com/a/whHQJFF

**Comportamento esperado**

Funcionar.

**Passos para reprodução**

Só usar os novos comandos de animações.

**Contexto**

Tava testando só.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.2
