### ISSUE TITLE
Uma solução para quem cai no limbo ou buga em baixo da construção em interiores personalizados

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#174]
**Descrição curta**
 Um comando para que o player, que bugou em interior personalizado, como por exemplo; caiu de limbo ou ficou sobre prenso no piso da construção, com o comando faz ele voltar para o mundo 0 para poder reentrar.

**Descrição detalhada**
 Muitos interiores personalizado acabam sendo pesados ou os players não botam tempo suficiente nos /config e também, as vezes buga e a mobilia te joga para fora da build (como já aconteceu muito comigo) então a ideia é que ter um comando que só funcionase SOMENTE dentro de um interior, ao digitar você seria teletransportado para o world 0 e na porta de onde você entrou.

**Como essa sugestão vai melhorar o servidor?**
 Evitaria o /SOS constante referente a isso e deixaria os players mais felizes, acredito eu.

**Comment by vitorvasc** [comment]
O ideal é que a pessoa sempre configure o tempo de congelamento via /config. Uma vez que este parâmetro é configurado, evita qualquer tipo de problema e o interior sempre carrega a tempo da pessoa não cair no limbo.

Infelizmente a adição deste comando poderia resultar em abuso por parte de jogadores mal intencionados em diversas situações de roleplay (perseguições, por exemplo).

**Comment by A-Noiva-Cadaver** [comment]
> O ideal é que a pessoa sempre configure o tempo de congelamento via /config. Uma vez que este parâmetro é configurado, evita qualquer tipo de problema e o interior sempre carrega a tempo da pessoa não cair no limbo.
> 
> Infelizmente a adição deste comando poderia resultar em abuso por parte de jogadores mal intencionados em diversas situações de roleplay (perseguições, por exemplo).

Desculpa ressuscitar mas, nem perto da porta? tipo um range minimo para o comando conseguir para ser ativado  e fazer a ação, um range que conseguiria tipo o player bugar em baixo do interior onde fica a /saida/entrada/ e o comando funcionará somente ali, para o player poder sair/fuga do local sem precisar de administrador e poder retornar depois
