### ISSUE TITLE
Celular tranca chat e interações

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#178]
**Versão do Servidor**

`Versão v1.7.3oa`

**Comportamento atual**

Ao fechar o celular com a caixa de texto do SMS selecionada, aberta e pronta para digitar, todas as outras interações dependentes do teclado (exceto andar e entrar em veículos) ficam trancadas, incluindo mas não limitado a abrir o chat, ligar/desligar veículos, trancar/destrancar veículos e propriedades, etc.

**Comportamento esperado**

Não deveria trancar.

**Passos para reprodução**

Abra a caixa de texto (na interface do celular) de SMS e feche o celular usando a seta para baixo.

**Contexto**

Estava apenas usando o celular normalmente.

**Solução possível**

Forçar o fechamento/delete da caixa de texto junto com o fechamento do celular.

**Comment by VictorFerraresi** [comment]
Corrigido com o rollback do celular.
