### ISSUE TITLE
Criação de comandos úteis

### ISSUE THREAD

**Issue by Ghostfvce** [Blaine-Life/blaine-issues#179]
**Descrição curta**
Alguns comandos a serem implementados para agilizar processos e/ou implementar novas funções.

**Descrição detalhada**
Criação dos seguintes comandos:
1. /des, linkado a função de /desligar como um atalho rápido para ligações.
2. /anrp para administradores que tenham acesso ao comando; anúncios de roleplay que possam ser interpretados pela comunidade

**Como essa sugestão vai melhorar o servidor?**
Agilizar processos e/ou implementar novas funções.

Obs: aos que tiverem ideias de outros comandos úteis, responderem o tópico.

**Comment by vitorvasc** [comment]
/anrp já foi previamente implementado.

Encaminharei a adição do /des juntamente com a issue https://github.com/Blaine-Life/blaine-issues/issues/170
