### ISSUE TITLE
ID de portas (True/False)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#18]
**Versão do Servidor**->
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
As portas trancáveis que são móveis ainda estão mostrando os IDs nessa versão.

**Comportamento esperado**
Deixar limpo pra jogar.

**Passos para reprodução**
https://prnt.sc/wghfg5

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
