### ISSUE TITLE
Saindo da facção/expulso não reseta o canal de rádio

### ISSUE THREAD

**Issue by matheussbdo** [Blaine-Life/blaine-issues#180]
**Versão do Servidor**

`Versão v1.7.3.oa

**Comportamento atual**

Eu sai da facção LSPD offline e quando loguei eu ainda tenho acesso ao rádio 911, algo que não deveria acontecer

**Comportamento esperado**

Ao ser expulso ou sair de uma facção, resetar a frequência SE ela for uma frequência governamental

**Passos para reprodução**

//

**Contexto**

//

**Solução possível**

Criar uma variável que ao sair da facção ou expulsar um jogador da facção todas as frequências governamentais que ele está sincado se desconectam.

**Comment by VictorFerraresi** [comment]
Não é bug, /sairfaccao e /demitir removem o canal do rádio normalmente, provavelmente o usuário foi removido da facção diretamente no banco de dados.
