### ISSUE TITLE
Carro voltando pra cor original depois de pintar

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#182]
**Versão do Servidor**

`Versão v1.7.3 Open Alpha`

**Comportamento atual**

Eu pintei meu carro na oficina do Mirror Park e estacionei o veículo na vaga dele, quitei do server e fiquei off por uns 30m e quando voltei o carro tava com a cor original de volta. (Branca)

prints: https://imgur.com/a/rQYwLDS

**Comportamento esperado**

O carro permanecer com a mesma cor.

**Passos para reprodução**

Pintar o carro e estacionar.

**Contexto**

Eu pintei meu carro na oficina do Mirror Park e estacionei o veículo na vaga dele, quitei do server e fiquei off por uns 30m e quando voltei o carro tava com a cor original de volta. (Branca)

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Não consegui reproduzir, provavelmente o servidor caiu/restartou no intervalo.
