### ISSUE TITLE
Simples sistema de /cumprimentar

### ISSUE THREAD

**Issue by SrMERLINI** [Blaine-Life/blaine-issues#187]
**Descrição curta**
Sistema de /cumprimentar com animação e /aceitar cumprimento

**Descrição detalhada**
Um sistema simples com animações de cumprimentos que deveria ser invitada por um e aceita por outro... Sinto muita falta desse sistema para o RP cotidiano.

**Como essa sugestão vai melhorar o servidor?**
Um sistema básico como esse trás uma melhor imersão na interpretação dos personagens. Com a gigantesca rama de animações do gta V podria auxiliar MUITO em Rp's de reconhecimento de membros de seletos grupos (Maçonaria, irmandade/fraternidade universitária, etc...)

**Comment by cybernitsche** [comment]
Já fiz uma sugestão como essa. Testei e listei as animações que poderiam ter esse tipo de enviar/aceitar, mas infelizmente não achei nenhuma anim de cumprimentar como aperto de mão, todas elas acabam sendo handshake — sem formalidade.
https://github.com/Blaine-Life/blaine-issues/issues/134

**Comment by VictorFerraresi** [comment]
Duplicada de #134
