### ISSUE TITLE
[IMPORTANTE] Economia Real

### ISSUE THREAD

**Issue by Adaill** [Blaine-Life/blaine-issues#188]
**Descrição curta**
  Uma Economia Real é o que proponho, para que a economia gire de VERDADE é preciso conhecer alguns princípios básicos como o da escassez e da ultilidade marginal que explicarei abaixo.

**Descrição detalhada**
 Quanto mais útil é um item e mais escasso, maaais ele tem valor. Porque nos servidores de RP todo mundo consegue TUDO bem fácil, porque todo mundo tem dinheiro, não existe aquela recompensa de dar duro numa negociação, se sair bem num trabalho para não ser demitido, fazer logística de recursos de uma empresa para ela não falir e até mesmo, logística de armas e venda de drogas de uma facção criminosa para vencer uma guerra. As coisas precisam ter utilidade para outro jogador QUERER comprar, não adianta simplesmente vender cocaína,, eu preciso que essa cocaína me dê um bônus por exemplo de correr mais, ter mais vigor ou até correr mais rápido (baseado em efeitos reais da cocaína) ser mais resistente a tiros, e ter muito mais tolerância no RP de ferido, porque estou noiado, além é claro de ficar chapado e viciado(ponto negativo das drogas que vai fazer uma pessoa comprar se não ela teria crises que PREJUDICAM ela de verdade).

Quando é fácil FARMAR dinheiro, cria-se um buraco na interpretação e uma inexplicação IC do dinheiro que aquele gangster conseguiu apenas esperando o salário cair na conta. Esse tipo de emprego BOT onde ninguém agrega nada, não trabalha pra ninguém, ninguém é beneficiado com o trabalho que vc faz apena o BOT do servidor e vc mesmo ganha dinheiro INFINITO por FARMAR faz com que o dinheiro do servidor tenha pouco, ou nenhum valor, perdendo o sentido de fazer iniciativas como essas para ganhar dinheiro, para negociar, ADMINISTRAR BEM a grana, porque é fácil, tá ali, pode até ser chato, mas com um esforço consegue. Não adianta deixar os empregos BOT cada vez mais chatos, o jogador vai perder muito tempo fazendo uma CHATICE do que se divertir fazendo um dinheirão vendendo coisas por exemplo.

Leiam livros de economia austríaca e evitem que o dinheiro do Blaine acabo com "dogecoin" ou até mesmo "real". transforme tudo em bitcoin fica a dica.

Fiz um post sobre isso num fórum do AD mas fui bem ignorado, deixarei lá pra terem mais uma ideia e a opinião de algumas pessoas que comentaram.
https://forum.advanced-roleplay.com.br/viewtopic.php?f=525&t=93196&p=1329140#p1329140 

**Como essa sugestão vai melhorar o servidor?**
 TUDO. Qual país você quer morar na vida real? Um que tem uma economia que FUNCIONE, você tem liberdade de abrir negócios que vão te dar rentabilidade (coisa que facções devem fazer para gerar emprego até mesmo civil, substituindo os bots dos empregos), vai gerar mais roleplay, muito mais interação entre os jogadores, relações de patrão-empregado, sindicatos, protestos, C A P I T A L I S M O. Sem falar que o dinheiro REALMENTE terá valor e as pessoas perseguirão o dinheiro com FOME

**Comment by vicezone7682** [comment]
"Leiam livros de economia austríaca"
ah, não. ancap querendo pagar de gênio não.
aliás: **ancap, não**.

**Comment by VictorFerraresi** [comment]
Sugestão de muito bom gosto, só vale ressaltar que ainda estamos em um jogo e nem tudo o que é 100% fiel a economia mundial atual é divertido.
