### ISSUE TITLE
Crafting de quase tudo

### ISSUE THREAD

**Issue by Adaill** [Blaine-Life/blaine-issues#189]
**Descrição curta**
 Crafting de TUDO principalmente armas e drogas.

**Descrição detalhada**
 Crafting complexo de armas, com FABRICAÇÃO e não compra de peças, drogas(plantações) e utilizando recursos naturais que podem ser minerados, e posteriormente processados (criação de sistema pra isso) que JOGADORES possam fazer e não comandos ou bots. Plantações massivas com riscos de falha das drogas.

Posteriomente um crafting de tudo que vende nas lojas, possibilitando a abertura de fábricas e indústrias que vão fornecer as lojas com seus materiais. A imaginação abre tudo.

**Como essa sugestão vai melhorar o servidor?**
 Vai criar interações profundas econômicas e interpretativas com fábricas clandestinas e ilegais.

**Comment by VictorFerraresi** [comment]
Foi entendido entre as facções que interagem com esses tipos de coisas que o que movimenta o roleplay deles é o item final, e não os trâmites produtivos.
