### ISSUE TITLE
Mensagem de confirmação para comprar/cancelamento

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#19]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Atualmente ao realizar uma compra na loja de roupas ou cancelar ela, não informa uma mensagem de confirmação.

**Comportamento esperado**
Acrescentar uma opção de confirmar se deseja comprar a roupa no slot desejado ou cancelar a compra na loja. Em testes, as teclas no menu estão muito sensíveis e durante edição, acabei por cancelar 2x sem querer, sendo que minha intenção era apenas retornar a uma página anterior.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
