### ISSUE TITLE
Escurecimento instantâneo do /telapreta

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#191]
**Descrição curta**
Quando o comando for confirmado pelo jogador, a tela ficar preta na hora.

**Descrição detalhada**
Remover o efeito de escurecimento e adicionar um efeito instantâneo do fundo totalmente preto.

**Como essa sugestão vai melhorar o servidor?**
Várias vezes eu já tirei screenshots com /telapreta antes da tela ter sido escurecida totalmente, o que atrapalha 100% na hora de tirar o fundo pra editar screens. Talvez pode ser só afobação minha, mas creio que deixe tirar esse efeito de "escurecimento" e fazer só escurecer de vez seja bem mais ágil.

**Comment by VictorFerraresi** [comment]
Implementada na 1.8.0oa
