### ISSUE TITLE
Personagem fica se mexendo na hora de trocar de roupa

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#194]
**Versão do Servidor**

`Versão v1.7.4.

**Comportamento atual**

Quando vc tá na loja de roupas e aperta um botão pra mexer o personagem ele fica travado e fica se mexendo sozinho, ele não sai do lugar mas fica virando toda hora e isso é ruim demais pra trocar a roupa do personagem, vc quer ver se tá daora ou se tá bem encaixado mas o personagem não para de se mexer.

**Comportamento esperado**

O personagem não ficar se mexendo toda hora.

**Passos para reprodução**

1 - Vá numa loja de roupas e navegue pelos menus.
2 - Escolha alguma roupa de seu gosto e mexa em algumas roupas, em seguida aperte qualquer um dos WASD, o boneco vai ficar se mexendo.

**Contexto**

É ruim pra trocar a roupa do personagem, ele não para quieto e fica meio ruim pra ver se a roupa tá boa ou não.

**Solução possível**

N/A.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.5 (congelamento removido)
