### ISSUE TITLE
/algemar congela o alvo

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#195]
**Versão do Servidor**

`Versão v1.7.5 OA`

**Comportamento atual**

Ao dar /algemar, o personagem alvo fica completamente congelado.

**Comportamento esperado**

Ao dar /algemar, o personagem alvo fica na animação de algemado e com o item nos pulsos, mas, ainda capaz de andar e interagir com o G em veículos policiais.

**Passos para reprodução**

- Algeme alguém.
- Peça pra essa pessoa tentar fazer qualquer movimento.

**Contexto**

Em todas as situações que envolvam pessoas algemadas, fica menos realista e quebra a imersão por não ter o personagem apropriadamente algemado.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.6
