### ISSUE TITLE
/pagarmultas só pode ser usado perto da PD

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#197]
**Versão do Servidor**

`Versão v1.7.5 OA`

**Comportamento atual**

As multas não podem ser pagas em qualquer lugar.

**Comportamento esperado**

As multas deveriam poder ser pagas em qualquer lugar.

**Passos para reprodução**

Multe alguém. Faça essa pessoa tentar pagar longe de um oficial.

**Contexto**

Vários players relatam não conseguir pagar multa em qualquer lugar.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
A multa foi feita para ser paga na prefeitura, ou, próximo a um policial. Enquanto o interior da prefeitura não é finalizado, só é possível pagar a multa próximo a um oficial.
