### ISSUE TITLE
/criarcena ser permanente e aumentar o alcance visual

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#198]
**Descrição curta**
Fazer o /criarcena ser um comando permanente, que não some após o GMX ou utilizar um comando diferente para isso, e também aumentar o alcance visual para conseguir ver um para alguns metros a mais.

Não sei se a intenção da cena ser removida após um GMX é para evitar flood ou coisa do tipo, se for, poderia adicionar um limite de quantas cenas um player comum pode criar e ele pode ver quais cenas ele criou e onde estão através de um comando tipo /vercenas. Donates poderiam criar mais.

**Descrição detalhada**
N/A.

**Como essa sugestão vai melhorar o servidor?**
Isso ajuda bastante a situar melhor o cenário ingame no qual um player se coloca e propor uma imersão um pouco maior, por exemplo, usar esse comando para descrever áreas grafitadas por gangues, ou locais fechados pelo LSPD, se um poste está com a luz apagada para o DET consertar, se um carro está vandalizado ou foi roubado, se uma casa foi arrombada, etc.

Mas se a cena some em todo GMX isso pode ser um problema.

Aumentar o alcance visual seria interessante também para quem está andando de carro conseguir ver cenas que foram criadas nas calçadas sem ter que praticamente entrar na calçada com o carro.

**Comment by VictorFerraresi** [comment]
O propósito do sistema é criar uma interação temporária em um local do mapa. O motivo de não ser persistente é que em um curto período, o mapa ficaria cheio de textos flutuantes e seria mais um processo pros admins cuidarem manualmente.
