### ISSUE TITLE
Comprando temporáriamente modificação pro carro sem ter dinheiro

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#2]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

Mesmo sem ter dinheiro para comprar uma modificação você consegue forçar um bug ao selecionar a modificação que interessa e quitar do servidor, assim quando voltar, ela estará no seu veículo.

**Comportamento esperado**

O ideal seria que se você não tem dinheiro, não efetue a compra e nem fique com a modificação no seu carro.

**Passos para reprodução**

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.2 open alpha
