### ISSUE TITLE
Emprego de Lixeiro

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#20]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Atualmente o /ajuda emprego não aparece o comando que é usado para iniciar o trabalho de lixeiro.

**Comportamento esperado**
Deveria constar quais os comandos são usados durante a rota para pegar o lixo e depois depositá-lo no local correto para receber a renda pelo trabalho feito. Para acréscimo, assim que você utilizar o /emprego no ícone, ele poderia já informar em uma mensagem automática o que o jogador deverá fazer, que é entrar dentro do caminhão e dar X comando para iniciar o trabalho.

**Passos para reprodução**
https://prnt.sc/wgi76o

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Emprego ainda não implementado.
