### ISSUE TITLE
Remover o crosshair da mira para as armas

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#203]
**Descrição curta**
Remover a mira crosshair das armas de fogo do servidor.

**Descrição detalhada**
N/A.

**Como essa sugestão vai melhorar o servidor?**
Aumenta a imersão do jogo, já que ninguém tem a mira perfeita, e também faria as troca de tiros serem ainda mais intensas e com riscos maiores de balas perdidas

**Comment by Campxs7** [comment]
Gostei. Se não for tirar a mira das armas, pelo menos tira do drive-by.

**Comment by Hayran** [comment]
Então é meio na mesma, porque aí o cara vai e baixa um programa que coloca mira no PC ou bota um ponto na tela.

**Comment by VictorFerraresi** [comment]
A gente já pensou nisso e chegamos na conclusão do Hayran acima, isso ia acabar criando mais disparidade do que já existe hoje.
