### ISSUE TITLE
/r pode ser ouvido de fora de veículos

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#205]
**Versão do Servidor**

`Versão v1.7.5 OA`

**Comportamento atual**

É possível ouvir o rádio de fora de veículos com janela fechada.

**Comportamento esperado**

Não deveria ser possível ouvir o rádio de veículos com janela fechada.

**Passos para reprodução**

Perspectiva 1: https://www.youtube.com/watch?v=wvGwRuMGEN0
Perspectiva 2 (olhar chat): https://cdn.discordapp.com/attachments/729575780484382732/827415012921311262/alt_V_Multiplayer_2021-04-02_00-37-49_Trim.mp4

**Contexto**

Os vídeos provêm o contexto.

**Solução possível**

Escreva aqui...

**Comment by A-Noiva-Cadaver** [comment]
Confirmo o bug, eu vi isso com o @LCPN

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.6
