### ISSUE TITLE
Multas não constam como pagas no MDC

### ISSUE THREAD

**Issue by mago1337** [Blaine-Life/blaine-issues#206]
**Versão do Servidor**

`Versão v1.7.5 OA`

**Comportamento atual**

Após pagar uma multa, ela ainda consta "em aberto" no MDC.

**Comportamento esperado**

Após pagar uma multa, ela deveria constar fechada/paga no MDC.

**Passos para reprodução**

Multe alguém, peça para pagar a multa, cheque no MDC.

**Contexto**

Muitas multas estão aparecendo em aberto no MDC, podendo ocasionar prisões injustas.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Correção já está aplicada no ambiente produtivo.
