### ISSUE TITLE
Staff member poder dar /checarferimentos quando em spec

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#209]
**Descrição curta**
O suport/admin poder usar o comando /checarferimentos pra ver os ferimentos e quem ele tá de spec.

**Descrição detalhada**

**Como essa sugestão vai melhorar o servidor?**
Dessa forma fica mais fácil um administrador que começou a observar a cena depois que os ferimentos já foram dados saber o que aconteceu, e daí ele poder tomar uma atitude caso haja falha no roleplay de ferido ou algo do gênero.

**Comment by doiska** [comment]
1.8.0 Open Alpha Hotfixes

**:sparkles: Adicionada checagem de ferimentos rastreável para administradores;**
