### ISSUE TITLE
Emprego de Entregador

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#21]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
• Após fazer as entregas dos pacotes e retornar a van, fica constando a mensagem de *Distance Left: XXXXXX*.
• Ao terminar a entrega, ao invés de receber na mensagem o valor que eu recebi de pagamento, ele informa: *$(payment)*
• Ao relogar durante a rota, os locais onde deveriam ser entregues os pacotes não aparecem no mapa e caso você volte para a empresa, você fica inviável de dar /carregarvan, pois informa que você precisa entregar os pacotes. Porém, caso você mude de veículo, você consegue prosseguir com uma nova rota normalmente.

**Comportamento esperado**
Creio que não era pra isso aparecer xD

**Passos para reprodução**
https://u.cubeupload.com/tiomarcelo/unknown.png
https://u.cubeupload.com/tiomarcelo/Screenshot2.png
https://u.cubeupload.com/tiomarcelo/a1eunknown.png

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
