### ISSUE TITLE
Sistema Weazel News + /noticias 

### ISSUE THREAD

**Issue by BelixKrux** [Blaine-Life/blaine-issues#210]
**Descrição curta**

Mudar o /noticias para amarelo ou laranja mais forte diferenciando dos outros chats (sugestão de cor HTML code #FFD700)
Acrescentar o /aovivo para colocar 1 ou mais participantes juntos na conversa do /noticias 

**Descrição detalhada**

A cor do /noticias em amarelo dourado vai dar um destaque, fazendo com que quem tenha em /config ativado o chat de noticias veja como tv de uma loja, tv de casa, rádio, jornal sobre algum acontecimento NAQUELE MOMENTO, isso gera mais RP entre quem está online, os curiosos vão pra cena ver de perto e movimenta o local. Se possível usem essa cor #FFD700.

Sobre o /aovivo eu gostaria de pedir pra dar uma diferenciada pequena na cor se possível usem essa cor #FFFF00.
**Como essa sugestão vai melhorar o servidor?**

Simplesmente pra atrair os curiosos que estão dentro do servidor para alguns acontecimentos dando mais ênfase pro que tá rolando no momento, seja um acidente, uma celebridade, uma votação de governo, um _evento_ grande criado pela equipe de eventos pretendendo envolver todos os jogadores e não confundir com vendas e eventos que vão acontecer em 2 dias ou 10 horas como costumam aparecer nos /anuncios feito pelos jogadores.

**Comment by vitorvasc** [comment]
Adicionado ao backloc.

**Comment by vitorvasc** [comment]
Alteração de cor do /noticias entrará no próximo update.

O comando entrevistar está no backlog.
