### ISSUE TITLE
Troca de personagem sem precisar fechar o alt?v e voltar tudo de novo

### ISSUE THREAD

**Issue by BelixKrux** [Blaine-Life/blaine-issues#211]
**Descrição curta**

Um comando /meuspersonagens da ao player acesso a um menu, ele pode escolher o novo personagem nessa tela, como se fosse um looby.
 
**Descrição detalhada**

O looby poderia ter alguns acessos rápidos ao donate, o personagem que ele está se torna um "ped" anda até não ter ninguém por perto e some _(ideia do ped é só um acréscimo rs)_.  
**Como essa sugestão vai melhorar o servidor?**

Vai reduzir a preguiça de continuar logado só porque trocar de personagem é mto cansativo, eu mesmo tava logado agora, mo preguiça de logar de novo só pq fechei, se não eu tava jogando até agora kkk

**Comment by VictorFerraresi** [comment]
A troca de contexto não é segura porque enquanto o jogador joga, diversas alterações são feitas em tempo real, baseado nas situações decorridas, no jogo dele. É impossível resetar todas essas modificações da engine sem o restart do jogo. Por esse mesmo motivo, o AltV bloqueia o debug mode (F8 > reconnect) de servidores que estejam na masterlist.
