### ISSUE TITLE
Cancelar volta ao personagem quando trocar /spec

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#213]
**Descrição curta**
Cancelar a volta ao personagem quando digitar /spec de id pra id.

**Descrição detalhada**
Quando der /spec em um e for passar pro próximo, em vez de ter que dar o comando 2x pela volta ao meu personagem, digitar apenas uma e já ir direto.

**Como essa sugestão vai melhorar o servidor?**
Agilidade 😞

**Comment by doiska** [comment]
Disponível na versão Open Alpha 1.8.0

^^
