### ISSUE TITLE
Mudança na exibição de usuarios no forum (opinião pessoal)

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#214]
**Descrição curta**
Voltar o tipo de formato que mostre mais detalhes sobre o player no forum.

**Descrição detalhada**
Voltar o tipo de formato que mostre mais detalhes sobre o player no forum, deixando evidente data de criação ou outras coisas que o jogador queira deixar evidente, **e** mostrar o nome escolhido pra UG do usuário. Atualmente existem 3 facções com UG vermelha no forum (weazel; CMG; FD), com essa alteração ficaria mais diferenciado, além de mais bonito.

**Como essa sugestão vai melhorar o servidor?**
Apenas opiniões pessoais estética para o forum.

**Comment by VictorFerraresi** [comment]
O software do fórum está sendo alterado.
