### ISSUE TITLE
Restaurante/Lanchonete Lucky Plucker com bug de interior e de empresa.

### ISSUE THREAD

**Issue by vicezone7682** [Blaine-Life/blaine-issues#215]
**Versão do Servidor**

`Versão v1.7.5 Open Alpha`

**Comportamento atual**

Ao entrar no Lucky Plucker, um restaurante Drive-thru próximo a Strawberry, você é teleportado para uma casa/quarto com cama, televisão etc. Além disso, não há opção para /comprar nada.

**Comportamento esperado**

Entrar num interior de restaurante e ter um ponto para o comando /comprar.

**Passos para reprodução**

É só dar /entrar na empresa Lucky Plucker.

**Contexto**

Meu personagem estava com muita fome, eu pensei em entrar lá e ter uma alimentação. No entanto, não foi possível devido à ausência de ponto com /comprar.

**Solução possível**

Acredito que seja bem simples: apagar o ponto da empresa, criar um novo. Dessa vez, com um interior de restaurante e o /comprar funcionando.

**Comment by vitorvasc** [comment]
Trata-se de uma empresa que ainda não foi comprada por nenhum outro jogador, portanto, não tem interior e nem posição para /comprar definidos.

A empresa será trancada pela Property Team e não deverá estar aberta até que seja comprada por um jogador.
