### ISSUE TITLE
Taser para LSPD

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#218]
**Descrição curta**
Disponibilizar a arma Taser para a LSPD

**Descrição detalhada**
Disponibilizar a arma Taser (não-letal) para que a LSPD, usando a própria taser do jogo.
De preferencia com o mod de skin para ficar igual ao taser real 
https://pt.gta5-mods.com/weapons/lapd-taser-green-gta-5-fivem

**Como essa sugestão vai melhorar o servidor?**
Vai permitir que policiais imobilizem suspeitos desarmados de forma real, sem usar força letal.

**Comment by mago1337** [comment]
Junto disso, sugiro também a alteração do cinto com taser atualmente na seção camisetas para o verde, compatibilizando os dois. Posso disponibilizar os arquivos separadamente.

**Comment by vitorvasc** [comment]
Adicionado no update 1.8.4 Open Alpha.
