### ISSUE TITLE
Emprego de Pescador

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#22]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Atualmente o /ajuda emprego não aparece o comando que é usado para iniciar o trabalho de pescador.

**Comportamento esperado**
Deveria constar quais os comandos que deveriam ser usados para iniciar a pesca no local e onde o jogador deveria ir para que esse comando funcionasse corretamente.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Emprego ainda não implementado.
