### ISSUE TITLE
SMS via celular (fim do /sms)

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#222]
**Descrição curta**
Remover a possibilidade de enviar SMS por comando direto do chat, devendo o player puxar o celular para enviar

**Descrição detalhada**
Remover a possibilidade de enviar SMS por comando direto do chat, devendo o player puxar o celular para enviar

Ou apenas adicionar /ame automático no envio do /sms

**Como essa sugestão vai melhorar o servidor?**
Atualmente o uso de /sms tem deixado os roleplays de abordagem com muito powergaming, sendo que os abordados avisam do local da cena sem que a polícia tenha condições de saber que está sendo enviado um SMS pelo abordado. Dessa forma, acabar com o /sms e deixar que tudo seja feito pelo celular vai deixar mais real, pois o policial vai ver que o outro jogador está usando o celular.

**Comment by A-Noiva-Cadaver** [comment]
É, puxar o celular causa mais trabalho e evitar o PG em situação, mas é foda as vezes quando o celular nem abre em pc low spec, acho que se tiver alguma possibilidade de quando mandar  o /SMS  dar alguma coisa específica vindo do player usando, para todos em torno

**Comment by VictorFerraresi** [comment]
Muito mais simples adicionar um /ame automático na submissão do SMS. Adicionado na 1.8.2oa
