### ISSUE TITLE
Mecânica na garagem da LSPD (tem carburador ou não tem carburador?)

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#223]
**Descrição curta**
Criar um ponto de reparo para as viaturas no interior da garagem da LSPD

**Descrição detalhada**
Permitir que oficiais reparem as viaturas no interior da garagem da LSPD

**Como essa sugestão vai melhorar o servidor?**
Vai evitar que as viaturas fiquem quebradas ad-eternum por falta de mecânicos ou impossibilidade de um roleplay detalhado sobre isso.

**Comment by A-Noiva-Cadaver** [comment]
Também para a Weazel news e Lsfd please :D

**Comment by vitorvasc** [comment]
Adicionado no update 1.8.4 Open Alpha.
