### ISSUE TITLE
Sistema de Ferimentos/Sangramento

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#224]
**Descrição curta**
Criar um sistema de vida mais detalhado e dinâmico, que permite o sangramento em diferentes escalas.

**Descrição detalhada**
Criar um sistema de vida mais detalhado e dinâmico, que permite o sangramento em diferentes escalas (superficial, baixo, médio, alto, extremo) que vai diminuir a barra de vida gradualmente caso não for tratado por um médico/fd.

Se não houver FD em trabalho, o player pode ir diretamente ao hospital, deitar-se na cama da enfermaria e aguardar o tratamento automático dos seus ferimentos.

Conceito: https://www.youtube.com/watch?v=Y2esvlP5sQw&ab_channel=veryinsanee
https://forum.cfx.re/t/release-body-damages-paid-standalone/2522416

**Como essa sugestão vai melhorar o servidor?**
Vai criar uma base para um sistema de vida muito mais detalhado quando puder sofrer adições no futuro.

**Comment by mago1337** [comment]
Conforme visto no vídeo, a interface é idêntica a um mod do Arma 3. Aqui o link para maior compreensão do conceito e seus mecanismos: https://ace3mod.com/wiki/feature/medical-system.html

**Comment by doougl4s** [comment]
Complemento de outra sugestão feita por mim: https://github.com/Blaine-Life/blaine-issues/issues/110

**Comment by VictorFerraresi** [comment]
Duplicado de #110
