### ISSUE TITLE
Tapete de Pregos para LSPD

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#225]
**Descrição curta**
Permite que policiais coloquem um tapete de pregos no chão para furar pneus de veículos

**Descrição detalhada**
Ao adicionar um tapete de pregos no chão, a polícia poderá furar o pneu de veículos fugitivos e neutralizar a perseguição com mais eficiencia. 

https://static.wikia.nocookie.net/gtawiki/images/4/4c/Spike-strips2-object-gtav.png/revision/latest/scale-to-width-down/640?cb=20140514163825

**Como essa sugestão vai melhorar o servidor?**
Vai deixar as perseguições mais reais e impedir longas fugas.

**Comment by vitorvasc** [comment]
Sugestão duplicada: https://github.com/Blaine-Life/blaine-issues/issues/202
