### ISSUE TITLE
Mudar a localização da loja de bicicletas

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#227]
**Descrição curta**
Mudar a loja de bicicletas para um local mais perto do centro do mapa, como colocar na loja que vende motos ou algum outro local mais próximo.

**Descrição detalhada**
N/A.

**Como essa sugestão vai melhorar o servidor?**
Novatos não vão precisar ir na pqp pra comprar uma BMX, isso salva tempo e dinheiro ingame.

**Comment by vitorvasc** [comment]
Encaminhado para a Property Team.

**Comment by VictorFerraresi** [comment]
Alterado ingame
