### ISSUE TITLE
Atm bugado

### ISSUE THREAD

**Issue by Meirinh4** [Blaine-Life/blaine-issues#23]
**Versão do Servidor**

`Versão v1.5.0`

**Comportamento atual**

ATM não abre a interface dele, somente o mouse fica mexendo

**Comportamento esperado**

Deveria abrir a interface normal do ATM, de saque, deposito e tals, mas não aparece nada, somente o mouse

**Passos para reprodução**

[link](https://cdn.discordapp.com/attachments/609333467355807755/795997227331223562/unknown.png
)
**Contexto**

Sacar dinheiro

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1 by @vanessa
