### ISSUE TITLE
Flexibilizar o /aj (Comando Administrativo)

### ISSUE THREAD

**Issue by SeHisoka** [Blaine-Life/blaine-issues#233]
**Descrição curta**
Fazer com que os administradores consiga responder o jogador direto pelo /aj (texto) — do que aceitar a solicitação e depois mandar /pm.

**Descrição detalhada**
Permitir que os administradores consigam responder as dúvidas dos jogadores diretamente pelo /aj.

**Como essa sugestão vai melhorar o servidor?**
Agilizando o comando, agiliza o suporte

**Comment by EduardoCirino** [comment]
Adicionado argumento opcional para o comando /aj enviar a resposta.
![image](https://user-images.githubusercontent.com/28939918/114321786-f817bb00-9af2-11eb-8ca4-c423eca5cc01.png)
