### ISSUE TITLE
Fim do GitHub

### ISSUE THREAD

**Issue by DiegoPcooper** [Blaine-Life/blaine-issues#235]
Primeiro de tudo, vocês já pararam pra perceber o número de sugestões o server tem por não se fácil a criação de conta nesse site? além disso dá uma leve preguiça de fazer isso tudo pra dar uma sugestão que as vezes vão ser simplesmente ignorada. Ao meu ver e ao ver de alguns que TAMBÉM CRITICARAM essa política de criação de sugestão ou até o bug support, é TÃO FÁCIL a criação de um tópico no fórum e a leitura das regras por lá que esse canal aqui chega ser inútil ou só uma coisa mais burocrática pra vocês evoluírem o server.

Outra coisa, tudo que recebemos do GitHub é em inglês e alguns não entendem  "bulhufas" do quê tá escrito. Bom... É isso, e enquanto não mudar simplesmente por ser chato fazer isso tudo por aqui minha sugestões não serão enviadas, como a de muitos players que também desistiram de mandar alguma sugestão por ser chato e difícil isso tudo aqui.

**Comment by A-Noiva-Cadaver** [comment]
É fácil criar conta aqui, é coisa de 30 segundos até e eles recebem bilhões de sugestões, mas eles tem prioridade ao que importa de fato primeiramente para sair do OpenAlpha o mais breve possível, deixar jogável e aberto  e aqui é mais fácil para eles por conta das classificações (tag) para por, para saber o que falta, se é possível, viável ou não e por ai vai, e o inglês básico todo mundo entende é a coisa mais fácil do universo é ter o inglês básico

**Comment by VictorFerraresi** [comment]
Sugestão fora do formato. 

O GitHub continuará sendo o nosso ponto focal para bug reports e sugestões. Se 180 issues implementadas e 87 issues em aberto são poucas pra você, te convido a ingressar a equipe de desenvolvimento do Gamemode pra nos ajudar a dar vazão \o/
