### ISSUE TITLE
O spawn de bicicleta é longe depois de comprar

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#237]
**Versão do Servidor**

`Versão v1.7.5 open alpha`

**Comportamento atual**

Ao comprar uma bicicleta no novo local da loja faz com que a bicicleta seja spawnada lá em Santa Maria.

**Comportamento esperado**

Spawnar na nova loja.

**Passos para reprodução**

Compra uma bike e spawna.

**Contexto**

Comprei uma bike na loja em Mission Row e ela spawnou lá em Santa Maria no antigo local

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido no último GMX
