### ISSUE TITLE
Bug na barbearia.

### ISSUE THREAD

**Issue by Nego08** [Blaine-Life/blaine-issues#24]
**Versão do Servidor**
`Versão 1.5.0 Open Alpha`

**Comportamento atual**

Fui usar a barbearia para editar o cabelo, quando eu cliquei em terminar, a tela do personagem foi para o pier mas o mapa mostrava que eu estava ainda na barbearia.

**Comportamento esperado**

Ao encerrar a edição, meu personagem iria aparecer na barbearia(A tela pelo menos).

**Passos para reprodução**

https://prnt.sc/wgu8ar

**Contexto**

Ficou impossível de fazer qualquer gameplay.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
