### ISSUE TITLE
z+ click para sentar em cadeira (dentro de propriedade)

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#241]
**Descrição curta**
z+ click para sentar em cadeira (dentro de propriedade)

**Descrição detalhada**
Atualmente já é possível sentar-se em cadeiras que estão espalhadas pelo mapa, mas isso pode ser melhor. Acredito que acrescentando a melhoria para usar dentro de propriedades vai agregar muito em bares, festas, além de roleplays em casa.

Para evitar que dê conflito no sistema de mobílias, é possível fazer uma checagem: Se você for o dono da casa OU tiver permissão para mobiliar, você clica z + click na mobília e ele abre um menu como o do veículo te perguntando se você quer editar aquela mobília ou se sentar nela. Deixando a opção de se sentar em primeiro lugar para evitar erros. 
Talvez seja de ajuda: Utilizar um filtro para que só apareça a opção SENTAR se o objeto for de alguma classe ligada a assentos/conforto

**Como essa sugestão vai melhorar o servidor?**
Dando mais artefatos para o imergir auxilia ainda mais no desenvolvimento do roleplay da comunidade em geral.

**Comment by vitorvasc** [comment]
Encaminharei para o @doiska pois já temos algo parecido sendo desenvolvido neste momento.

**Comment by doiska** [comment]
> 1.8.0 Open Alpha Hotfixes
> **Adicionado sistema de animações com posicionamento (/sentar, etc);**
> Range do /dl duplicada;
> Adicionada checagem de ferimentos rastreável para administradores;
> Corrigido bug que limitava a conexão a 18 jogadores;
> Corrigido bug no /r invisível;
> Corrigido bugs no Cruise Control;
> Corrigido bug no /copiarchaves;
> 

Adicionamos um novo meio para o uso de animações.
Obrigado pela sugestão
