### ISSUE TITLE
Cruise Control funciona após desligar o carro

### ISSUE THREAD

**Issue by Mad-zi** [Blaine-Life/blaine-issues#244]
`Versão v1.8.0 Open Alpha`

**Comportamento atual**
Se ativar o Cruise Control, desliga o carro, ele continua funcionando, ignorando o facto do carro estar desligado

**Comportamento esperado**
Ao desligar o motor com o cruise control ligado, ele se desligue também.

**Passos para reprodução**
Liga o carro (y), acelera até conseguir ativar o Cruise Control (Ctrl), desliga o carro (y), **sem carregar** em algo que desative o cruise control, com (S) ou (Space Bar) ou (Ctrl)

**Contexto**
--

**Solução possível**
Ao desligar o carro (y) desligar o Cruise control

**Comment by Mad-zi** [comment]
PS: Também é possível ligar o Cruise Control com o carro já desligado, desde que esteja a cima da velocidade para ativar ele, penso que 10km/h

**Comment by A-Noiva-Cadaver** [comment]
Confirmo o bug, qualquer um pode fazer que é na certa que ocorre
https://www.youtube.com/watch?v=XpONqV8V1EA

**Comment by EduardoCirino** [comment]
Fix será implementado no próximo patch.
