### ISSUE TITLE
Bug no Control Cruise que não tá fazendo efetivo com direção no mouse (0% de prioridade)

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#245]
**Versão do Servidor**

`Versão v1.8.0 oa`

**Comportamento atual**
Tá funcionando certinho, tirando por dois problemas, dirigir com mouse e veículo com motor desligado (Bug que não é 
 prioridade)

**Comportamento esperado**
Era para ele continuar acelerando o carro e travado a velocidade mesmo dirigindo com o mouse.

**Passos para reprodução**

Bote o jogo para dirigir pelo mouse ou apenas clique no esquerdo do mouse, que habilita a condução pelo mesmo, trava a velocidade e vai indo dirigindo, você notará que o veículoi vai perdendo a essência da velocidade até parar totalmente, se você largar, ele não retorna a dar um gás mas no momento que tu toca no W para andar, ele retorna a acelerar e trava de novo na velocidade que foi pedida e acontece novamente e fica nesse loop, caso dirigir com o mouse.
Evidência: https://www.youtube.com/watch?v=Eabu6USmH54

**Contexto**

Não me afetou em nenhum problema, apenas que eu adoro dirigir pelo mouse e acho muito melhor e realista, ainda mais com o cruise ativado seria uma enorme diferença como se fosse simulação mas infelizmente para dirigir com o mouse e o cruise é F

**Solução possível**

Não sei sobre solução desse problema, apenas desenvolvedores e management vão saber o que fazer

**Comment by EduardoCirino** [comment]
Fix será implementado no próximo patch.
