### ISSUE TITLE
Multas pagas consta a pagar

### ISSUE THREAD

**Issue by adrielcasser** [Blaine-Life/blaine-issues#249]
**Versão do Servidor**

`Versão v1.8.0`

**Comportamento atual**

Multas q ja foi paga consta q não foi paga para os policiais.

**Comportamento esperado**

Estar correto no sistema dos policiais, mostrar q foi pago e as que não foi.

**Passos para reprodução**

https://i.imgur.com/WNLRv0r.jpg

**Contexto**

Bug.

**Solução possível**

Correção de bug.

**Comment by VictorFerraresi** [comment]
Corrigido e implantado
