### ISSUE TITLE
/ooc, /areparar, /setarvida, /proximo e Emprego GoPostal bugado na linha de pagamento

### ISSUE THREAD

**Issue by Kevboy1337** [Blaine-Life/blaine-issues#25]
**Versão do Servidor**

`Versão 1.5.0`

**Comportamento atual**

 /ooc, /areparar, /setarvida, /proximo, não funcionando para Game Admin 1.

Emprego GoPostal com falha de escrita no pagamento, aparecendo a linha de código $(payment)

**Comportamento esperado**

Todos os comandos supracitados com as permissões setadas para Game Admin 1 e o emprego GoPostal na hora do pagamento aparecer quanto o jogador em questão tem que receber.

**Passos para reprodução**

Todos os comandos citados aparece que não é um administrador aplicando o comando.

GoPostal
https://media.discordapp.net/attachments/765309306315997204/796108351569920000/Grand_Theft_Auto_V_Screenshot_2021.01.05_-_16.43.32.09.png?width=840&height=473

**Contexto**

Resolver a linha de comando na imagem citada acima, e setar permissão para os comandos citados para GM 1.

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Os comandos de administrador não serão alterados.
Texto corrigido na 1.5.1
