### ISSUE TITLE
Regras no fórum referenciam uma "regra 13" inexistente

### ISSUE THREAD

**Issue by vicezone7682** [Blaine-Life/blaine-issues#250]
**Versão do Servidor**
v1.8.0 Open Alpha

**Comportamento atual**
A regra 13 é referenciada na regra 2 de PG, mas ela não existe.

**Comportamento esperado**
Que tenha uma regra 13 ou que a referência a ela seja cortada.

**Passos para reprodução**
Só entrar no fórum, na publicação das regras: [https://forum.blaine.life/viewtopic.php?f=6&t=5](https://forum.blaine.life/viewtopic.php?f=6&t=5)

**Contexto**
Não me afetou, só percebi isso quando fui reler as regras.

**Solução possível**
Criar uma regra 13 ou consertar a regra 2.

**Comment by vitorvasc** [comment]
Corrigido.
