### ISSUE TITLE
Aumentar o montante permitido em assaltos

### ISSUE THREAD

**Issue by vicezone7682** [Blaine-Life/blaine-issues#251]
**Descrição curta**
Aumentar a quantidade de dinheiro que pode ser subtraída em assaltos.

**Descrição detalhada**
Hoje em dia, o máximo, em assaltos, é três mil dólares. Considerando que recebemos 1,400 por hora (civil sem facção ou empresa oficial), isso significa aproximadamente duas horas apenas (desconsiderando o auxílio novato, já que é tudo antes do nível 20). Duas horas logado, ainda mais hoje sem sistema ANTI-AFK, é muito de boa. Isso se o cara não trabalhar, aí ele recupera... A sugestão envolve aumentar para que seja mais assustador carregar grandes quantias de dinheiro, como - pelo menos - $5000~$8000 dólares. Isso faria com que o realismo e diversos ramos interpretativos (criminal, civil, policial) fossem valorizados e mais aprofundados.

**Como essa sugestão vai melhorar o servidor?**
Os jogadores não andariam com tanto dinheiro no bolso, seriam mais realistas em relação a isso. Além disso, o roleplay criminal e policial ficaria mais animado - já que um jogador que foi assaltado perdeu umas 5 horas no jogo, então ele iria atrás da polícia para caçar o criminoso (os criminosos fugindo, a polícia indo atrás). A Weazel News poderia fazer notícias sobre áreas mais perigosas, com maior incidência de assaltos, esse tipo de coisa. Ou seja, o cenário do roleplay fica mais rico como um todo.

**Comment by BelixKrux** [comment]
Seria interessante poder roubar até mais que 5k uns 50k no assalto, assim poderiam ter mais cuidado com o próprio dinheiro, guardar no banco, na casa (atualização de armazenamento) e até mesmo pra empresas grandes, contratarem o serviço de carro forte com segurança armada pra carregar o dinheiro até o banco, entre outras ideias.

**Comment by VictorFerraresi** [comment]
Sim galera, realmente não seria nem um pouco frustrante você sacar 50.000 que você ficou horas trabalhando pra comprar um carro e ser roubado com 100% de chance.

As limitações existem porque um servidor de roleplay possui uma criminalidade infinitamente mais concentrada do que uma cidade da vida real. Quantas vezes vocês já foram assaltados com 50 mil reais no bolso?

**Comment by VictorFerraresi** [comment]
Os valores serão revistos, mas já adianto que vocês jamais vão ver um limite de 50.000 para roubos aqui.

**Comment by vicezone7682** [comment]
eu nunca falei de 50k. eu literalmente fui minimamente audacioso na minha sugestão

**Comment by vanessa** [comment]
@vicezone7682 foi em relação ao que @BelixKrux falou, não você
