### ISSUE TITLE
/sentar - ao puxar o celular, a anim reseta e então, tem que dar F e refazer e posicionar de novo

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#254]
**Versão do Servidor**

`Versão v1.8.0 oa`

**Comportamento atual**

/Sentar tudo certinho, movimenta certo, posiciona certinho, porém ao puxar o celular, a animação dá stop e tem que dar F e refazer.

**Comportamento esperado**
Que não resete-se a animação do /sentar que estiver sentado no tal onde seja o que for

**Passos para reprodução**

 usa o /sentar, não precisa nem posicionar, basta puxar o celular e guardar
https://youtu.be/XGentPWk1-4

**Contexto**

O bug em sí não me afetou porém, creio que deveria funcionar ao guardar o celular corretamente, tendo o contínuo anim escolhido ali no /sentar

**Solução possível**

I dont know, apenas quem fez o sistema vai saber solucionar xD

**Comment by EduardoCirino** [comment]
Foi adicionado um temporizador para sincronizar a animação a cada 10 segundos dentro no do sistema de edição de anims.
As alterações estão para entrar no próximo patch.
