### ISSUE TITLE
Controle de Cruzeiro deixa o carro morrer na subida

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#255]
**Versão do Servidor**

`Versão v1.8.0 oa`

**Comportamento atual**

O veículo na subida, com controle de cruzeira, seja em qualquer velocidade e dependendo do quão ingrime é subida, ele acaba por parar de funcionar e deixar o carro morrer no meio da subida. Apenas ligue em certa velocidade, pegue uma subida e vai...

**Comportamento esperado**

Era para velocidade ser travada literalmente e o carro literalmente ser 'forçado' a subir na marra, mesmo com seu peso ou pela subida seja agressiva ou pacífica.

**Passos para reprodução**

 Acione o controle, suba um morro por exemplo, em alguns segundos o carro morre e o controle continua ativo e não tem força para subir mais o carro.
https://youtu.be/fPs5yMpAG2Y

**Contexto**

Fazer o controle de cruzeiro começar forçar o motor mesmo na subida, sem deixa-lo morrer durante.

**Comment by EduardoCirino** [comment]
Um rework no sistema de `Cruise Control` já está em revisão para entrar no servidor.
Agradeço.
