### ISSUE TITLE
/sentar não funcionando nem se tiver com "um" pé sobre qualquer água, seja piscina rasa, praia, piscina funda e por ai vai

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#256]
**Versão do Servidor**

`Versão v1.8.0 oa`

**Comportamento atual**

O /sentar não funciona sobre quando personagem está sobre a água, seja rasa ou profunda

**Comportamento esperado**

Que o sistema desse, para poder se sentar sobre as escadas/assentos da piscina seja rasa ou meio rasa e também, sobre a beirada do mar. 

**Passos para reprodução**

 Encoste pelo menos UM dos pés do personagem somente em água rasa e tente, se não funcionar tente entrar mais

**Contexto**

 Não tá dando para deitar/sentar sobre beiradas de piscinas rasas e sobre a beirada do mar de Santa Maria e e.t.c.

**Solução possível**

  Fazer o sistema bloquear de funcionar /me somente quando tiver realmente fundo, a ponto de fazer a natação.

**Comment by EduardoCirino** [comment]
Corrigido.
Entrará no próximo patch.
