### ISSUE TITLE
/sentar /deitar /relaxar /lean + z+Click com objetos que consiga sentar

### ISSUE THREAD

**Issue by Mad-zi** [Blaine-Life/blaine-issues#257]
`Versão v1.8.1 Open Alpha`

**Comportamento atual**
Dei upload do vídeo para ser mais especifico - https://www.youtube.com/watch?v=_jVkFaeHHXo

**Comportamento esperado**
Ao estar a usar alguma animação com edição, sejam as atuais disponíveis /sentar /deitar e /relaxar, não ser possível interagir com objetos como bancos ou cadeiras para sentar

**Passos para reprodução**
Aqui - https://www.youtube.com/watch?v=_jVkFaeHHXo
1- /sentar /lean /relaxar /deitar, algum dos possíveis com edição
2- Usar o sistema de Z+click para interagir com algum objeto que seja possível sentar.
3- Ao clicar nas setas, direito ou esquerda, a animação mudará, porem nas duas animações, na do primeiro passo e do segundo, logo o personagem teleporta entre as duas como no vídeo.

**Contexto**
N/A

**Solução possível**
Ao estar a usar seja o 1º ou o 2º passo, não ser possível interagir com outros objetos como bancos ou cadeiras, ou então ser possível usar o Z+click e anular o comando do 1º passo.

**Comment by EduardoCirino** [comment]
Corrigido, entrará no próximo GMX.
