### ISSUE TITLE
Veiculo sem combustivel continua a rodar

### ISSUE THREAD

**Issue by adrielcasser** [Blaine-Life/blaine-issues#259]
**Versão do Servidor**

`Versão v1.8.2`

**Comportamento atual**

Ao terminar o combustível o veiculo continua ligado e andando normalmente e não sendo possível de desligado.

**Comportamento esperado**

Acabar o combustivel= veiculo desligar automaticamente, ou quando tivesse na reserva o veiculo falhar o motor.

**Passos para reprodução**

O veiculo já sem gasolina rodando normalmente, utilizei a tecla que faz o desligamento do motor e aparece esse aviso "Este veiculo esta sem combustivel"
https://i.imgur.com/w0UlVjw.jpg
E na hora de abastecer, ele abastece com o veiculo ligado (já que nao é possivel desliga-lo com falta de comsustivel).
https://i.imgur.com/6hwEBc5.jpg

**Contexto**

Não deixou um RP legal, ficou como um combustivel infinito.

**Solução possível**

Correção de bug.

**Comment by EduardoCirino** [comment]
Corrigido para o próximo GMX.
Obrigado.
