### ISSUE TITLE
Portas do Departamento do LSPD

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#26]
**Versão do Servidor**
`Versão v1.5.0 Open Alpha`

**Comportamento atual**
Mesmo sendo o líder do LSPD, diz que não possuo permissão para destrancar portas do Departamento de Mission Row. Acredito que esteja assim para todos os cargos, apesar de não ter testado.

**Comportamento esperado**
Polícia pode tudo né...

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Não é bug, preciso setar a facção como dona da propriedade. Será atualizado no próximo GMX.
