### ISSUE TITLE
Animações com objetos attached para a Weazel News

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [Blaine-Life/blaine-issues#262]
**Descrição curta**
 ao digitar por exemplo.. /animweazel (1-tal) - toca uma animação especifica com um item que casa com a anim

**Descrição detalhada**
Ao digitar um comando especifico /animweazel (pode ser outro), dá play na animação com o item especifico, por exemplo camêra no ombro, tem uma animação para isso com o devido objetos e o mesmo para microfone e acho que para luz e outros também, no momento não tenho os ids mas deixarei sugestão aqui já para quem for achando os devidos, botar aqui. 

**Como essa sugestão vai melhorar o servidor?**
Ajudará em um rp para Weazel ao vivo futuramente e noticias por vídeos ICly (rp)

**Comment by VictorFerraresi** [comment]
Esse sistema já existe ingame, solicite pra um Senior Administrator+ a setagem dos objetos para os membros da facção. Basta digitar /usar [id] que o objeto e a animação serão aplicados.

Itens disponíveis:
Microfone Weazel
Câmera de Transmissão
