### ISSUE TITLE
Sem cinto na van do emprego caminhoneiro

### ISSUE THREAD

**Issue by adrielcasser** [Blaine-Life/blaine-issues#267]
**Versão do Servidor**

`Versão v1.8.3`

**Comportamento atual**

Ao procurar o cinto na van (**/cinto**), não foi encontrado (**"Esse veículo não possui cinto de segurança"**).

**Comportamento esperado**

Ter o cinto de segurança para o motorista.

**Passos para reprodução**

https://i.imgur.com/t7PVSsF.png

**Contexto**

Sem cinto, sem RP do /checarcinto para o policial já que não há cinto.

**Solução possível**

Colocar o /cinto.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.8.4oa
