### ISSUE TITLE
Reavaliação nos valores das casas

### ISSUE THREAD

**Issue by DiegoPcooper** [Blaine-Life/blaine-issues#268]
- Casas estão com valores sem sentido, 300k uma mansão e pra morar em outros lugares de classe média 200k

-Sugestão: Fazer um reavaliação nos valores das casas e aproveitar o momento de reavaliação já setar os valores nas casas para evitar a burocracia de ter que vir ao fórum pra solicitar sei que tem muitas casas ao menos a maioria ou em lugares que devem ser popularizados já devem estar setados. Fazer com que trailers custassem mais ou menos ($5.000) e pela levar em consideração a distancia de Los Santos, isso fará com que pessoas decidam comprar casas no interior e movimentará as rodovias. Casas no interior ou dependendo da localidade (Meio do nada) Não passarem de $35,000 e se for uma facção que queira interagir naquele lugar, dar uma "ajuda de custo" para que eles estejam motivados pra isso. Precisamos de movimentação e os valores das casas estão desequilibrados. Uma casa em rockford é 300k e dependendo da casa em Miror Park e 260k uma casa em Monte Gordo **MEIO DO NADA** 565k

**Comment by SeHisoka** [comment]
Boa tarde.

**Sobre a reavaliação dos valores as propriedades:**

**I.** As propriedades, principalmente as casas do servidor já passaram por dois processos de reavaliação para chegarem ao preço que está hoje. É inviável deixar ainda mais barato as casas que por sua parte, devem ter sua própria valorização dentro do cenário do servidor.

**II.** Atualmente um novo processo de reavaliação nos valores das propriedades é infactível. Os preços que jogadores creiam ser abusivos ou até mesmo fora do comum para a propriedade pode ser tratado diretamente e unicamente com o Head of Property.

**Sobre a realização de solicitações de valores & setagem de todas as propriedades do GTA V:**

**I.** Hoje a solicitação de valores mediante o fórum servem unicamente para dois propósitos: Registro dos jogadores com comprometimento de suas propriedades e manter a área de propriedades em ordem, deixando a equipe ciente de quais propriedades são setadas, que jogadores solicitam, etc. Existe todo um controle interno sobre.

**II.** Não vou dizer que é humanamente impossível realizar a setagem de todas as casas já com seu preço in-game, mas é um trabalho desnecessário visto que se estas não tem preço, significa que não tem um jogador interessado na propriedade visto que existe uma solicitação básica no fórum para sua aquisição. A administração ocupa mais de um papel dentro do servidor, priorizando acima de tudo o suporte ao jogador. Hoje o jogador tem um acesso extremamente fácil para adquirir uma propriedade desde que tenha interesse nesta, por isso, 

**Sobre ajuda de custo & auxilio com projetos de facções/empresas:**

**I.** A equipe de propriedades já auxilia os projetos dos jogadores do jeito que pode, não fugindo muito das regras internas da equipe. Trabalhamos juntamente do jogador para tentar além de disponibilizar com mais facilidade a propriedade, também orientar este sobre as regras e instrui-lo sobre o auxilio que a equipe fornece inicialmente. O jogador **apenas** precisa entrar em contato com algum membro da Property Team e tirar suas dúvidas. Queremos e faremos com que os projetos dos nossos jogadores sejam realizados.

Para mais informações, você pode entrar em contato com algum [membro da Property Team](https://forum.blaine.life/topic/413-equipe-property-team/?tab=comments#comment-3147) e sanar o que tiver de dúvidas referente a qualquer processo e/ou procedimento que a equipe adota.
