### ISSUE TITLE
Após ser preso algemado, fico algemado infinitamente.

### ISSUE THREAD

**Issue by Mad-zi** [Blaine-Life/blaine-issues#269]
**Versão do Servidor**

`Versão v1.8.3 OpenAlpha`

**Comportamento atual**
Fui preso na cela algemado, não conseguia fazer animações, continuava a dizer que estava algemado, acabei por sair e mesmo cá fora continuava a dizer que estava algemado, mesmo estando sem algemas.

**Comportamento esperado**
Após ser colocado na cela as algemas continuarem visíveis para a policia retirar, ou serem removidas automaticamente.

**Passos para reprodução**
Apenas ser algemado e ser preso na cela por X tempo, e vai ficar algemado pra sempre, mesmo não sendo visivel as algemas nem a animação.

**Contexto**
Queria fazer animações na sela e não conseguia, sai da prisão e não consigo fazer nada pois estou algemado.

**Solução possível**
"Após ser colocado na cela as algemas continuarem visíveis para a policia retirar, ou serem removidas automaticamente."

**Comment by VictorFerraresi** [comment]
Corrigido na 1.8.4
