### ISSUE TITLE
Chapéu some ao entrar em veículo

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#27]
**Versão do Servidor**
`Versão v1.2.35 alpha`

**Comportamento atual**

Toda vez que o jogador que possui algum chapéu equipado em seu personagem e entra em algum veículo, o chapéu some. Tudo bem que existe o comando "/chapeu" só que é algo chato de ficar fazendo toda hora, a cada vez que entra em algum veículo.

**Comportamento esperado**
Era pro personagem entrar no veículo e continuar com o chapéu equipado.

**Contexto**
Bom, em uma situação de roleplay, imagine que você equipou uma capacete, a cada hora que você entrar/sair de um veículo, você vai ter que ficar dando /chapeu

**Solução possível**
Só arrumar isso mesmo, ao entrar no veículo, continuar com o chapéu equipado.

**Comment by VictorFerraresi** [comment]
É comportamento padrão do GTA:V pra tratar chapéus que atravessariam o teto do carro. Nesse caso, faz mais sentido deixar o jogador ter a oportunidade de usar o /chapeu pra escolher se quer ou não mostrar, evitando que apliquemos isso de maneira automática, bugando alguns modelos
