### ISSUE TITLE
Alteração da lore do servidor para dias atuais/modernização

### ISSUE THREAD

**Issue by thug-thug** [Blaine-Life/blaine-issues#282]
**Descrição curta**

O servidor precisa trazer um ar de modernidade e coleções de mods modernos e atraentes para promover um novo tipo de gameplay que possa atrair jogadores, se manter em uma lore antiga em um jogo que traz diversas coisas da atualidade não promove muito.

**Descrição detalhada**

Cada vez mais a comunidade de texto se esvazia por diversos motivos, cultivamos players de vários servidores passados e de servidores ativos, mas, o que não pensamos ainda é que continuamos a mesma coisa que os outros. Não mudamos praticamente nada, mesmo estilo sempre, nada de interessante. Tudo bem que o servidor é em outra plataforma e com certeza trás total diferença de gameplay, porém, parece algo antigo da mesma forma em que se baseia na lore. Precisamos trazer um ar de modernidade tanto em modificações como em vivência da vida dentro do jogo, isso de fato vai ser o diferencial e atrair jogadores, a staff deve pensar como modernizar o servidor e trazer isso para o nosso lado, como referência temos vários servidores de fivem que podem ajudar em buscar as informações. 

**Como essa sugestão vai melhorar o servidor?**

Eu só viso o crescimento do servidor bastante atrativo.

**Comment by Hayran** [comment]
O GTA V é moderno oras, não estamos em 1992 do GTA SA.

**Comment by vitorvasc** [comment]
Quando falamos sobre a lore do servidor estamos basicamente falando de tudo o que o universo do GTA 5 proporciona.

Basta dar uma rápida olhada na [wiki](https://gta.fandom.com/wiki/Grand_Theft_Auto_V) mais popular do jogo podemos ver que o universo é muito extenso. Existem diferentes marcas para veículo, roupas, celular e empresas dos mais variados gêneros (transporte, segurança e bancos são alguns exemplos).

Estamos no início do servidor e é natural que estes pontos ainda não estejam 100% explorados. O papel da equipe é entender cada vez mais o ambiente fornecido pelo GTA 5 para que possamos replicar este mesmo ambiente ao servidor.

Adicionar novos mods, que muitas vezes diminuem a performance dos computadores mais fracos, seria dar um passo maior do que a perna e com isso deixaríamos de aproveitar tudo o que o jogo nos oferece.
