### ISSUE TITLE
Bug de formatação e #404

### ISSUE THREAD

**Issue by SrMERLINI** [Blaine-Life/blaine-issues#285]
**Versão do Servidor**
`Versão v1.8.4

**Comportamento atual**
Bug de formatação do fórum ou 404 Not Found

**Comportamento esperado**
Formatação correta e página informativa.
**Passos para reprodução**
1º situação:  Link informativo para criar Inssue dando 404 (  * https://github.com/Blaine-Life/blaine-issues/blob/master/README.MD)
2º situação: Formatação do forum nos seguinte tópico
 * https://forum.blaine.life/topic/9-leia-antes-de-postar/?tab=comments#comment-11
**Contexto**
N/A
**Solução possível**
Atualização do topico/URL

**Comment by vanessa** [comment]
> 1º situação: Link informativo para criar Inssue dando 404 ( * https://github.com/Blaine-Life/blaine-issues/blob/master/README.MD)

@SrMERLINI Onde você está vendo esse link?

**Comment by SrMERLINI** [comment]
Quando você vai criar um Issue aqui ele envia esse link para estarmos cientes da formatação e regras...

**Comment by vanessa** [comment]
Corrigido.
