### ISSUE TITLE
Taxi foi respawnado automaticamente após um certo tempo andando pela cidade.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#29]
**Versão do Servidor**
`Versão v1.2.35 alpha`

**Comportamento atual**
Simplesmente eu estava andando pela cidade, até bati e quebrei o taxi na qual eu estava, e deu o meu paycheck e do nada o taxi respawnou comigo dentro e me mandou de volta a Central de Taxis, estacionado na vaga, fiquei sem entender. Inclusive com o tune que eu utilizei no LS Custom, que reportei no outro issue que estava tudo de graça.

**Comportamento esperado**
Bom, o taxi não era pra respawnar assim, não sei se é porque eu fiquei parado com ele por muito tempo e dentro dele. Mas não é pra respawnar do nada, só se não tiver ninguém dentro.

**Passos para reprodução**
Infelizmente não consegui gravar, nem tirar print do momento.

**Contexto**
Estava caçando bug's pelo servidor, dei um alt+tab, quando volto do alt+tab, meu payday tinha caido, o taxi respawnado comigo dentro e eu estava de volta na central de taxis com o taxi totalmente consertado e na vaga.

**Solução possível**
Bom, não é pra acontecer isso, como falei, é pro taxi respawnar só se não tiver ninguém dentro.

**Comment by fmd00** [comment]
Corrigido na 1.5.2
