### ISSUE TITLE
/dar bugado, dando pra dar itens de longe

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#3]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

Básicamente você consegue bugar o comando /dar fazendo com que ele entregue o seu item determinado para o outro player onde quer que ele esteja.

**Comportamento esperado**

Deveria funcionar apenas se o player estiver a X distância de você

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790062188903006228/unknown.png](url)

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.0 alpha
