### ISSUE TITLE
Ao digitar /entrar em frente a porta do hospital, você é jogado para um interior de apartamento

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#30]
**Versão do Servidor**
`Versão v1.2.35 alpha`

**Comportamento atual**
Ao chegar em frente a porta do hospital e digitar /entrar ou apertar o K você é mandado para um interior de apartamento

**Comportamento esperado**
Não é pra ter esse /entrar no hospital, é pra ser o interior só, abertão ou que seja trancado para ninguém abusar desse bug. Já pensou? O cara ta fugindo da policia e mete uma dessa pra se esconder?

**Passos para reprodução**
Em frente a porta do hospital
![image](https://user-images.githubusercontent.com/76986308/103776089-b6680780-500d-11eb-8e68-8cf318773f21.png)
Ao dar o /entrar e ir para esse interior
![image](https://user-images.githubusercontent.com/76986308/103776138-c97ad780-500d-11eb-81d6-3662492c36f6.png)

**Contexto**
Apenas fui testar os comandos no hospital, porém acho que também não está funcional, afinal cheguei lá dentro e dei /curar e nada aconteceu.

**Solução possível**
Trancar a propriedade.

**Comment by VictorFerraresi** [comment]
Porta vinculada à porta física do hospital na 1.5.1
