### ISSUE TITLE
Colocar as opções possíveis para o /portamalas

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#31]
**Versão do Servidor**
`Versão v1.2.35 alpha`

**Comportamento atual**
O comando /portamalas não aparece as possíveis opções de utilização, como "colocar, abrir, ver". Se tiver algum novato no servidor, ele provavelmente não vai saber utilizar

**Comportamento esperado**
Que apareça as opções para a utilização do /portamalas

**Passos para reprodução**
![image](https://user-images.githubusercontent.com/76986308/103777009-0bf0e400-500f-11eb-966d-6ad64bc8407d.png)

**Contexto**
Só fui abrir o /portamalas para dar uma olhada.

**Solução possível**
Colocar as opções para a utilização do /portamalas

**Comment by MacLove13** [comment]
Comentário:
As possíveis opções hoje só aparecem quando você tenta uma que não existe.
Seria bom aparecer as opções apenas ao dar /portamalas mesmo.

**Comment by VictorFerraresi** [comment]
Implementado na 1.7.5
