### ISSUE TITLE
Arsenal (LSPD)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#33]
**Versão do Servidor**
`Versão v1.5.0`

**Comportamento atual**
O arsenal do LSPD não está setado no Departamento onde ele deveria estar.

**Comportamento esperado**
N/A

**Passos para reprodução**
https://prnt.sc/wi1b03

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Não é bug. Armário criado na 1.5.1
