### ISSUE TITLE
Ammunation

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#34]
**Versão do Servidor**
`Versão v1.5.0`

**Comportamento atual**
A compra de armamentos (pistolas e escopeta) está liberado para qualquer jogador na loja de armas, o que deveria ser restrito com um porte controlado.

**Comportamento esperado**
N/A

**Passos para reprodução**
https://prnt.sc/wi1egv

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.1
