### ISSUE TITLE
Animações

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#35]
**Versão do Servidor**
`Versão v1.5.0`

**Comportamento atual**
Não consta no comando de /ajuda qual é o comando para checar as animações já pré-definidas e também não existe um comando para checar todas as animações disponíveis.

**Comportamento esperado**
N/A

**Passos para reprodução**
https://prnt.sc/wi1gju

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Adicionado /animlist na 1.5.1
