### ISSUE TITLE
Troca de comandos (/taxi & /cancelartaxi) + adição sobre ligar a um mecânico

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#36]
**Versão do Servidor**
`Versão v1.5.0`

**Comportamento atual**
Realizar a troca do comando /taxi para usar o telefone para ligar para um taxista ou mecânico, fazendo com que tenha números pré-definidos, como 1222 para taxistas e 555 para mecânicos.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Inviável enquanto o sistema de telefones públicos não estiver implementado, novos jogadores não possuem celular e não conseguirão solicitar um taxi.
