### ISSUE TITLE
/hq (LSPD/LSFD)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#37]
**Versão do Servidor**
`Versão v1.5.0`

**Comportamento atual**
Acrescentar o /hq no sistema de rádio atual para que seja interpretado como Central, ampliando o roleplay das facções governamentais.

**Comportamento esperado**
O texto padrão de início poderá ser simplificado desta forma: [CH: 911] Dispatch: - e na sequência já aparecer o que você escreveu.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by fmd00** [comment]
Adicionado no próximo patch.
