### ISSUE TITLE
Interior do LifeInvader não carregado

### ISSUE THREAD

**Issue by vanessa** [Blaine-Life/blaine-issues#38]
**Versão do Servidor**

`Versão v1.5.0 Open Alpha`

**Comportamento atual**

![image](https://user-images.githubusercontent.com/23136832/103983800-add61500-5164-11eb-822d-ee8c09ca6198.png)

**Comportamento esperado**

Acho que era pra estar carregado. Testei local apenas.

**Comment by VictorFerraresi** [comment]
IPL adicionado na 1.5.2
