### ISSUE TITLE
Estado inconsistente nos chamados de taxista

### ISSUE THREAD

**Issue by vanessa** [Blaine-Life/blaine-issues#39]
**Versão do Servidor**

`Versão v1.5.1 Open Alpha`

**Comportamento atual**

![image](https://user-images.githubusercontent.com/23136832/104111278-f570b400-52be-11eb-92ce-55d284e6c987.png)

**Comportamento esperado**

**Passos para reprodução**

1. Digite /aceitartaxi de alguém
2. Digite /cancelartaxi. Vai aparecer que você não tem nenhum chamado ativo.

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
Oi Vane! Esse comportamento é esperado porque o /cancelartaxi é utilizado pela pessoa que chamou o taxi pra cancelar o chamado, e não o contrário! Caso você, como motorista, queira abandonar o serviço, é só digitar /cancelarcorrida!
