### ISSUE TITLE
Comandos para remover acessórios

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#4]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

Ao usar alguns comandos de acessórios específicos e removê-los, o server não seta uma barriga ou braços para o personagem, fazendo com que ele fique com partes invisiveis.

**Comportamento esperado**

Deveria setar a roupa de numero 15 para que ele não fique invisivel. Ou seja, caso ele for masculino setar a jaqueta 15 caso ele de /jaqueta e setar o a camiseta 15 caso ele dê /camiseta também.

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790063241707520030/unknown.png](url)

**Contexto**

**Solução possível**

Fazer uma solução para que o sistema não permita que o jogador fique com o bone invisivel e sete o número 15 para ele (masculino) (no caso de femininos tem que achar o numero correto) mas para corrigir o bug basicamente colocar a jaqueta 15 caso ele retire a jaqueta, calça 15 e assim por diante... evitando sempre que fique como nulo, ou invisivel caso o jogador não tenha comprado nenhuma vez na loja esse torso, calça ou afins

**Comment by Maict** [comment]
Fiz um teste e descobri que se você ficar invisivel na parte do torso, usando o /torso você reverte o bug. Daria para colocar uma mensagem avisando isso ao jogador novo que acaba caindo neste bug, sei lá. De qualquer forma, não é mais totalmente um bug.

**Comment by VictorFerraresi** [comment]
Não é um bug, o comando apenas dá toggle na peça de roupa digitada.
O toggle é =
Retira a roupa escolhida (Não é sempre NULL, cada peça possui um ID específico, para cada sexo, para remoção, exemplo: 15).
Ou
Reaplica a roupa escolhida.

O /torso deve ser usado para dar toggle também no torso caso você deseje que este apareça completamente.
