### ISSUE TITLE
LSPD (Comandos)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#40]
**Versão do Servidor**
`Versão v1.5.1 Open Alpha`

**Comportamento atual**
• A Heckler & Koch MP5A3 não equipa.
• A Mossberg 590 vem apenas com 12 munições (dá pra inserir 30 munições) e a Accuracy International AW-F vem com 5 (dá pra inserir 15 munições).
• O /armario não possuí o Taser X26.
• Ao relogar/crashar, as armas da PD somem.
• O /frequencia não autoriza sintonizar diferentes frequências em diferentes canais, portanto o /r-1-2-3-4 ficam sempre a mesma frequência. Acredito que é o sistema geral e não algo voltado somente pra facção.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
SMG corrigida na 1.5.3
