### ISSUE TITLE
Nickname dos jogadores sumindo.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#41]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
Os nicknames tão sumindo conforme um tempo que passa.

**Comportamento esperado**
Era pro nick ficar aparecendo e não sumindo.

**Passos para reprodução**
N/A

**Contexto**
Fica dificil saber quem é quem, se os nickname some.

**Solução possível**
Que os nicknames fiquem aparecendo sempre.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.3
