### ISSUE TITLE
Bugs no sistema de digitação do celular

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#42]
**Versão do Servidor**

`v1.5.1 Open Alpha`

**Comportamento atual**
1- Quando você digita uma pensagem muito grande no celular, em vez do chat parar no limite e continuar embaixo, ele continua e gera um bug que puxa o chat pra direita sempre que a página de mensagens é aberta.

2- Ao enviar uma mensagem e apertar ESC, você começa a digitar no chat do jogo e no chat do celular. (inclusive esse bug corta a animação de digitar)

**Comportamento esperado**
1- Que a linha respeitasse o limite e eventualmente não precisando puxar a tela pra direita.

2- Que você não pudesse digitar no chat do jogo enquanto tivesse digitando no celular após apertar esc 

**Passos para reprodução**
Segue o vídeo meu parceiro: https://www.youtube.com/watch?v=LxkGE3-fr6U

**Contexto**
<!--- Como este problema te afetou? O que você estava tentando fazer?
O chat sendo puxado toda hora que abro ele, e uma coisa que não era pra acontecer... Tava tentando mandar mensagem.

**Solução possível**
1- Fazer o celular respeitar o limite de texto por linha

2- Não dar esse bug aew quando apertar ESC.

**Comment by MacLove13** [comment]
Comentário:
Mesmo sem pressionar ESC, após mandar algumas mensagens, o controle do jogo é reativado e em quanto você digita uma nova mensagem as teclas ficam funcionais. (Mudando camera, abrindo chat, trancando carro)

**Comment by vanessa** [comment]
Será corrigido no próximo GMX.

**Comment by vanessa** [comment]
@cybernitsche @MacLove13 Podem confirmar que isso foi corrigido, por gentileza?

**Comment by cybernitsche** [comment]
Aparentemente o problema com a quebra de linhas e o de andar digitando com o celular foi resolvido, PORÉM, agora, depois de clicar em alguma coisa dentro do celular, a câmera fica livre e começa a mexer igual um trem de maluco enquanto tu fuça no celular. Arrasta pra cima que eu te mostro como ficar rico(brincadeiras a parte, vídeo do bug): https://www.youtube.com/watch?v=ccH3nCBOsHY


Queria aproveitar esse espaço e já dar uma sugestão: Quando a gente apertar /c pra abrir o celular, existir um comando (ex: /cc) pra gente poder alterar pro controle da câmera/personagem. Ou seja: /c abre o celular, /c fechar o celular; /cc eu altero entre: controlar o personagem e controlar o cursor pelo celular. 
Não sei se ficou bem de entender, mas é isso. 💪

**Comment by cybernitsche** [comment]
Acho que essa câmera solta ainda faz parte do que o Alligator disse, de controlar o personagem após algumas mensagens, se prestar atenção em 0:43 do vídeo eu ando com o personagem, e nem tinha prestado atenção nisso.

**Comment by vanessa** [comment]
Comportamento esperado de desbloquear a câmera porque não significa que você está apenas lendo as mensagens que você não pode olhar para outros lugares ou apertar <kbd>F1</kbd> para poder andar.
