### ISSUE TITLE
erro de flag em algumas animações + erro de comando de animação

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#43]
**Versão do Servidor**

`v1.5.1 Open Alpha`

**Comportamento atual**
/gsign = flagueado errado
/comer = andando com o personagem
/apoio não é o suficiente para a animação

**Comportamento esperado**
/gsign = que a animação fosse exibida uma vez e depois mantesse ela, sem looping
/comer = que o personagem se mantesse parado enquanto come
/apoio = só dar /apoio fosse o suficiente, e não precisar acrescentar algo mais, já que não há variações dele

**Passos para reprodução**
Segue o link meu parceiro: https://www.youtube.com/watch?v=yE2cgtIAktM

**Contexto**
Tava tentando fazer anim

**Solução possível**
Respondido no Comportamento esperado

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.3
