### ISSUE TITLE
Beber cerveja e depois pegar o celular causa um bug visual em que o celular fica na sua mão pra sempre até vc relogar

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#45]
**Versão do Servidor**

`Versão v1.5.1 open alpha`

**Comportamento atual**

Se vc pegar uma cerveja e depois abrir o celular e fechar, a cerveja fica invisível na sua mão e vc consegue beber, pra fazer ela aparecer de novo vc precisa usar /usar de novo e o celular buga na mão do usuário, ficando permanentemente na outra mão. Esse bug só afeta o visual do jogador, perguntei aos meus amigos em cena e eles disseram que não estavam vendo o celular.

**Comportamento esperado**

O celular não ficar na minha mão. Uma print minha: https://www.upload.ee/image/12745423/GTA5_2021-01-10_00-27-01-56.png
Reparem na mão direita.

**Passos para reprodução**

Não consegui gravar um vídeo na hora e não vou conseguir gravar agora, são 02am e tô com sono kkkk é capaz de amanhã eu esquecer. Mas os passos é:

1 - Pega uma cerveja e usa ela, dá uns golês.
2 - Pega seu celular, faz qualquer coisa nele e guarda.
Se tudo ocorrer "bem" a cerveja sumiu da sua mão mas vc ainda consegue beber.
3 - Da /usar na cerveja dnv e usa o celular mais uma vez. É isso.
**Contexto**

Não afetou muito mas atrapalhou screenshots que tirei por causa do celular bugado.

**Solução possível**

Não sei...............

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.9
