### ISSUE TITLE
/rtc

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#46]
**Versão do Servidor**
`Versão v1.5.1 Open Alpha`

**Comportamento atual**
O /rtc atual mantém o veículo ligado, o que consome combustível. Fazer com que o veículo spawne desligado.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.5
