### ISSUE TITLE
/s (sussurrar)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#47]
**Versão do Servidor**
`Versão v1.5.1 Open Alpha`

**Comportamento atual**
Atualmente o /s não aparece o ID do jogador que enviou ou recebeu o sussurro, seria interessante acrescentar, já que fica mas prático digitar o ID e não o nome do jogador para digitar a mensagem.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Implementado na 1.5.3
