### ISSUE TITLE
Boombox

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#49]
**Versão do Servidor**
`Versão v1.5.2`

**Comportamento atual**
Ao usar a boombox e cancelar a edição dela para colocar no chão, você fica inviável de usá-la, você precisa relogar para que consiga editar novamente.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by fmd00** [comment]
Corrigido no próximo patch.
