### ISSUE TITLE
/ajuda radio exibe /ajuda atalhos junto com sua mensagem

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#5]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

Este é um bug simples, ao usar o comando /ajuda radio ele exibe os comandos que funcionam com o rádio mas errôneamente exibe os comandos do /ajuda atalhos

**Comportamento esperado**

É pra exibir só o /ajuda radio

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790067536334553088/unknown.png](url)

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.1 alpha
