### ISSUE TITLE
Deslogar e logar faz com que spawne em lugares aleatórios certas vezes

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#51]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
Eu desloguei e spawnei em um local totalmente aleatório do que eu tinha deslogado no login anterior. Ou seja, é bem estranho isso.

**Comportamento esperado**
Logar e deslogar aonde você quitou.

**Passos para reprodução**
N/A

**Contexto**
Pode afetar em roleplays alheios, imagine você crashar no meio de uma situação policial e aí spawnar em um local aleatório. É complicado.

**Solução possível**
Logar e deslogar aonde você quitou.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.3
