### ISSUE TITLE
Mobilias sumindo

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#52]
**Versão do Servidor**

`v1.5.2 Open Alpha`

**Comportamento atual**
Quando você começa a mobiliar e coloca um certo tanto de objetos, ao deslogar algumas mobilias somem.

**Comportamento esperado**
Que as mobilias nunca fossem removidas até que a pessoa de fato o faça.

**Passos para reprodução**
Só ir mobiliando, quando tiver bastante mobilias (sla, constrói uma estrutura) e depois de um tempo deslogue, quando logar de novo algumas coisas podem ter sumido. Acho que isso acontece depois de outro bug, que é quando você coloca uma mobilia e em vez de ir direto pra edição dela, ela some, e tu só pode ver ela depois de relogar ou entrar e sair da casa, algo assim.
print de mobilias que sumiram:https://cdn.discordapp.com/attachments/651230385543315456/798076815569715200/Grand_Theft_Auto_V_Screenshot_2021.01.11_-_03.31.52.59.png

**Contexto**
Toda hora tem que ficar colocando as mesmas mobilias, e sempre que reloga elas somem de novo, fazendo assim um looping de: colocar, sumir, colocar, sumir.

**Solução possível**
Sla, faz parar de sumir man.

**Comment by cybernitsche** [comment]
Adição, depois de tentar continuar mobiliando e colocar +2 mobilias, o chão também sumiu, então pelo visto quanto mais coloca, mais some.
https://cdn.discordapp.com/attachments/651230385543315456/798080265669836821/unknown.png

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.4
