### ISSUE TITLE
VW diferente / Interior bugado

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#53]
**Versão do Servidor**
`Versão v1.5.2 Open Alpha`

**Comportamento atual**
Mesmo em um outro world, dentro de um interior de casa que foi setado em cima da residência para edição, aparece todos os comandos de chat, como /b, chat normal, /me, /do, etc.

**Comportamento esperado**
Num era pra aparecer.

**Passos para reprodução**
https://prnt.sc/wkqn49

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.3
