### ISSUE TITLE
Veículo se teletransportando

### ISSUE THREAD

**Issue by MacLove13** [Blaine-Life/blaine-issues#54]
**Versão do Servidor**
`Versão v1.5.2 Open Beta`

**Comportamento atual**
O veículo spawnado é deixado desocupado, trancado e com o motor desligado, e some do local, aparecendo em outro, intacto, trancado e desligado.
Dando a entender que o mesmo não foi roubado ao dirigido até o local, e sim teletransportado.

(Possivel Causa)
Parece que ele salva a posição de algum em algum tempo, e por algum motivo o carro volta para uma posição antiga (que o carro estava parado ou andando).

**Comportamento esperado**
Deveria permanecer onde foi deixado.

**Passos para reprodução**
Ande de carro pela cidade, estacione ele e deixe lá por bastante tempo.
(Local testado onde ocorreu 2x: Próximo ao GC Postal)

**Contexto**
N/C

**Solução possível**
N/C

**Comment by VictorFerraresi** [comment]
Corrigido (possivelmente) na 1.5.3
