### ISSUE TITLE
Emprego de entregador com bug te kickando.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#55]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
Fui testar o emprego de entregador e aí quando finalizei todas as entregas e cheguei no destino final para receber o pagamento, apareceu uma imagem me kickando.

**Comportamento esperado**
Que não kickasse.

**Passos para reprodução**
![image](https://user-images.githubusercontent.com/76986308/104287117-c14eec00-5494-11eb-99c6-2c61dd23aed1.png)

**Contexto**
N/A

**Solução possível**
Que não tenha kick.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.4
