### ISSUE TITLE
Objeto do celular não aparece ao dar /c

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#56]
**Versão do Servidor**

`v1.5.3 Open Alpha`

**Comportamento atual**
Quando puxa o celular ele não aparece na mão como deveria.

**Comportamento esperado**
Que o objeto do celular aparecesse na mão do personagem.

**Passos para reprodução**
/c
print do meu celular não aparecendo e o da outra pessoa também não:
https://cdn.discordapp.com/attachments/437456523141316609/798685396601929758/unknown.png

**Contexto**
Fui tentar mexer no celular e não apareceu.

**Solução possível**
Fazer o objeto aparecer 👍

**Comment by cybernitsche** [comment]
Aparentemente foi um bug que eu forcei no meu jogo por estar testando muitas animações. Pode fechar, foi mal aew.

**Comment by VictorFerraresi** [comment]
O celular não está aparecendo pelo mesmo motivo que as mobílias. Corrigido junto com o bug das mobílias.
