### ISSUE TITLE
impossível editar mobília 

### ISSUE THREAD

**Issue by GabrielAparecido36** [Blaine-Life/blaine-issues#57]
**Versão do Servidor**

`Versão v1.5.4 Open Alpha
**Comportamento atual**

No momento em que eu dou /mobilia, escolho alguma mobília  e compro ela, porém ela não aparece para ser editável, eu volto para o /mobília e vou na opção para editar livre e a mobília não aparece para ser editada e quando vou na opção de edição por Menu, nada acontece eu não consigo usar mais o chat.

**Comportamento esperado**

A mobilia aparecer para ser editada.

**Passos para reprodução**

https://youtu.be/ze3_IxVonNw

**Contexto**

Tentando mobiliar minha casa.

**Solução possível**

Escreva aqui...

**Comment by alansiq** [comment]
Problema corrigido IG
