### ISSUE TITLE
Calças do personagem sumiram

### ISSUE THREAD

**Issue by doougl4s** [Blaine-Life/blaine-issues#59]
**Versão do Servidor**

`Versão v1.5.4`

**Comportamento atual**

Comprei uma conjunto de roupas na binco, joguei um tempo e desloguei. Quando loguei novamente as calças haviam sumido (invisivel)

**Comportamento esperado**

A calça deveria ficar salva no conjunto de roupas, assim como as demais peças de roupas.

**Passos para reprodução**

Eu não consigo dizer exatamente qual foi o drawable que comprei.

**Contexto**

Eu precisei voltar na binco e comprar outra calça para corrigir o problema.

**Solução possível**

Verificar se as calças estão salvando.

**Comment by alansiq** [comment]
Calça ID 42 ped masculino

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.8 (bug relacionado a escolher uma textura inexistente para aquela roupa).
