### ISSUE TITLE
/ajuda propriedade não funciona

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#6]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

O comando /ajuda propriedade simplesmente não funciona, não mostra nada.

**Comportamento esperado**

Devia mostrar os comandos auxiliares das propriedades

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790068219578417162/unknown.png](url)

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.1 alpha
