### ISSUE TITLE
Validação ao solicitar spawn de um veículo

### ISSUE THREAD

**Issue by alansiq** [Blaine-Life/blaine-issues#60]
**Versão do Servidor**

`Versão v1.5.4 Open Alpha`

**Comportamento atual**

É possível abrir a /v lista e, com ela aberta, vender o veículo a outro player e, então tentar spawnar o veículo vendido.

![image](https://user-images.githubusercontent.com/36564924/104468496-48d05400-5596-11eb-9c33-177afd199662.png)

**Comportamento esperado**

Uma tratativa para tentar spawnar um veículo que não é seu (validar se existe tratativa para tentar spawnar um veículo já spawnado).

**Passos para reprodução**

1. Spawnar um veículo
2. Abrir /v lista
3. /vender veiculo para outro player
4. Selecionar o veículo vendido na lista
5. Ser kickado do servidor conforme imagem acima.

**Contexto**

Não estava conseguindo fechar a /v lista de nenhuma outra forma (ESC, setas, etc) então optei por clicar em um veículo para tentar me livrar da /v lista. Assim que encontrei o erro.

**Solução possível**

- Botão sair na /v lista
- 
- Adicionar uma validação e tratativa ao tentar selecionar um veículo que não te pertence na /v lista

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.5
