### ISSUE TITLE
Posto de combustível "/comprar" ao invés de "/abastecer"

### ISSUE THREAD

**Issue by alansiq** [Blaine-Life/blaine-issues#61]
**Versão do Servidor**

`Versão v1.5.4 Open Alpha`

**Comportamento atual**

Blip de abastecimento nos postos de combustível aparecem como "/comprar" mas o comando é "/abastecer"

**Comportamento esperado**

Blip mostrar o comando "/abastecer"

**Passos para reprodução**

Ir em qualquer posto de gasolina validar o blip (Propriedade 1279 por exemplo)

**Contexto**

Fui abastecer e não sabia qual o comando.

**Solução possível**

Alterar o texto do blip ou remover completamente.

![image](https://user-images.githubusercontent.com/36564924/104496950-6ca49180-55b8-11eb-94ed-e6452359575c.png)

**Comment by fmd00** [comment]
Corrigido no próximo patch.
