### ISSUE TITLE
Erro de sincronização

### ISSUE THREAD

**Issue by LuliCarey** [Blaine-Life/blaine-issues#62]
**Versão do Servidor**

`Versão v1.5.4`

**Comportamento atual**

Erros de sincronização. Eu estou em um lugar x e, no jogo do meu amigo, estou em lugar y. Isso para não falar das animações, às vezes danço no meu jogo e no do meu amigo estou parado, aí tenho que ficar repetindo a animação pra ver se vai (e nem sempre isso acontece, o que é MUITO frustrante).

**Comportamento esperado**

Se eu usei uma animação, eu espero que ela apareça no jogo do meu amigo também. Só isso. 

**Passos para reprodução**

Não tem muito o que mostrar. É justamente o que eu narrei ali. 

**Contexto**

Dar /striptease na esquina, com minha personagem prostituta. Não funcionava no jogo dos outros, o que muitas vezes afasta clientes.

**Solução possível**

Consertar isso aí.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.7
