### ISSUE TITLE
/rtc parou de funcionar.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#63]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
O /rtc parou de funcionar para os suportes

**Comportamento esperado**
Que a equipe de suporte possa utilizar

**Passos para reprodução**
Fala que não tem autorização para utilizar o comando administrativo

**Contexto**
N/A

**Solução possível**
Que volte a funcionar

**Comment by fmd00** [comment]
Corrigido no próximo patch.
