### ISSUE TITLE
Personagem quebra o vidro do carro após destrancar

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#64]
**Versão do Servidor**

`Versão v1.5.5 Open Alpha`

**Comportamento atual**
Quando você tenta entrar no seu próprio carro e ele tá trancado, o personagem faz a animação de tentar abrir, até aí normal, mas se você após ele fazer a animação, destrancar o carro, ele vai quebrar o vidro do próprio carro.

**Comportamento esperado**
Que em vez de quebrar o vidro do carro, a animação de arrombamento ser cortada ali, e não continuar pra você destrancar e quebrar o vidro do carro.

**Passos para reprodução**
Já explicado, mas pra um visual, no vídeo: https://www.youtube.com/watch?v=a1v3hOZK_l8

**Contexto**
É questão estética, ninguém quer ficar andando com o carro com vidro quebrado porque destrancou o carro logo após ver que tava trancado. Por mais que seja algo simples, particularmente me incomoda, e acredito que não seja só a mim. Por enquanto respawnar o carro faz o vidro consertar, mas e quando o emprego de mecânico for implementado e o carro parar de se recuperar ao ser estacionado? Vamos precisar de mecânico pra arrumar o vidro que nós mesmos quebramos sem querer.

**Solução possível**
Uma solução que pensei seria literalmente remover essa parte da animação de arrombamento do gta padrão (quebrar o vidro d carro), já que no servidor o furto de veículos não vai funcionar dessa forma; tentar a maçaneta e quebrar, e sim por sistema, o que faz essa animação inútil em questão de utilidade, e fazendo as pessoas quebrarem o vidro do carro.

**Comment by alansiq** [comment]
É possível replicar esse bug com frequência - sempre que você destranca o veículo enquanto o personagem ainda está dentro da animação.

1.  Tentar entrar em um veículo trancado
2. Destrancar o veículo ainda durante o início da animação / enquanto o personagem encosta na porta


Caso não seja possível remover a animação de arrombamento, uma solução possível seria bloquear a animação de "forçar" a fechadura de veículos trancados (impedir que tentem entrar nele como um todo)

**Comment by mago1337** [comment]
Posso reforçar que é facilmente replicável.

**Comment by fmd00** [comment]
Corrigido no próximo patch.
