### ISSUE TITLE
/hq da facção LSFD ser enviado no rádio 911 ao invés do 910

### ISSUE THREAD

**Issue by matheussbdo** [Blaine-Life/blaine-issues#65]
**Versão do Servidor**

`Versão v1.5.5.oa`

**Comportamento atual**

Quando é dado /hq na facção LSFD a mensagem é enviada no canal 911 ao invés do 910.

**Comportamento esperado**

Se a facção for LSFD do membro que der o comando /hq, enviar uma mensagem de rádio de Dispatch no rádio 910.

**Passos para reprodução**

—.

**Contexto**

—.

**Solução possível**

—.

**Comment by alansiq** [comment]
Eu, como civil, recebi mensagens de /HQ da LSFD hoje. "[LSFD] teste"

Por favor validar se todos estão recebendo ou se administradores deveriam receber.

**Comment by fmd00** [comment]
Corrigido no próximo patch.
