### ISSUE TITLE
Pillbox Hill Medical Center (PHMC) com as portas fechadas após GMX

### ISSUE THREAD

**Issue by matheussbdo** [Blaine-Life/blaine-issues#66]
**Versão do Servidor**

`Versão v1.5.5.oa

**Comportamento atual**

Após todo GMX as portas do Pillbox Hill Medical Center retornam com as portas fechadas, o tornando inacessível.

**Comportamento esperado**

Que não exista nenhuma tranca para o hospital, afinal lá será onde os jogadores irão curar e o LSFD realizar atendimentos breves e entrega de pacientes.

**Passos para reprodução**

—.

**Contexto**

—.

**Solução possível**

Desabilitar a tranca do hospital ou tornar as portas abertas após qualquer GMX.

**Comment by alansiq** [comment]
Porta 1:
Porta ID 14 / Propriedade ID 14
[19:19:29] model is 661758796
[19:19:29] type is 3
[19:19:29] pos is 356.531 -591.596 27.797
[19:19:29] 485378


Porta 2:
Porta ID 1336
[19:20:57] model is -487908756
[19:20:57] type is 3
[19:20:57] pos is 299.228 -585.932 42.284
[19:20:57] 497922

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.6
