### ISSUE TITLE
Propriedade ID 857 - Dono não tem permissão para acessar o inv

### ISSUE THREAD

**Issue by alansiq** [Blaine-Life/blaine-issues#67]
**Versão do Servidor**

`Versão v1.5.5 Open Alpha`

**Comportamento atual**

Proprietário da casa 857 (Earnest Keefer) reportou não conseguir utilizar o sistema de inventário da casa com mensagem de erro "Não sou dono da propriedade" ao tentar conferir o armazenamento.

Poderiam conferir se houve algum erro humano ou erro de sistema, essa casa passou por uma alteração de interior recentemente.

Já verifiquei que:

1. As duas portas de acesso pertencem a mesma propriedade
2. As duas portas estão destinadas para a mesma DIM (id da propriedade 857)
3. O proprietário consegue trancar e destrancar as duas portas de acesso.

Não consegui identificar mais nenhuma etapa para corrigir esse problema IG.

**Comportamento esperado**

Poder conferir o armazenamento.

**Passos para reprodução**

Validar se a propriedade 857 pertence a Earnest_Keefer / por que tem controle sob as portas e não sobre seu inventário.

**Contexto**

N/A

**Solução possível**

N/A

**Comment by VictorFerraresi** [comment]
Corrigido ingame, não aparenta ser bug de script.
