### ISSUE TITLE
Bug no armário do LSFD

### ISSUE THREAD

**Issue by dggDiego** [Blaine-Life/blaine-issues#68]
**Versão do Servidor**

`Versão v1.5.5 Open Alpha`

**Comportamento atual**

Ao pegar os equipamentos no armário do LSFD o usuário recebe objetos diferentes do listado. Por exemplo, ao selecionar a lanterna, você recebe uma faca (é o erro mais gritante), ao selecionar pra pegar o martelo você recebe o pé de cabra, ao selecionar pra pegar o pé de cabra, você ganha um martelo.

**Comportamento esperado**

Os itens da lista deveriam entregar ao jogador o que está descrito.

**Passos para reprodução**

Acho que não é difícil de entender ou validar a existência do bug.

**Contexto**

Tentava pegar os itens da minha facção e não consegui obter a lanterna, além de ter obtido os demais itens totalmente desconexos com o descrito na lista.

**Solução possível**

Só colocar a lanterna pra vir quando selecionado lanterna e reordenar os demais itens.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.6
