### ISSUE TITLE
Hitkill com porrada na moto, seja com arma ou sem.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#69]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
Ao utilizar alguma moto e tentar dar um chute, coronhada com arma, bater com alguma arma branca, você dá automaticamente hit kill em algum jogador. Algo que eu acho particularmente muito apelão. Devia ser nerfado com um dano menor ou retirado.

**Comportamento esperado**
Que tenha um dano muito menor ou que seja retirado.

**Passos para reprodução**
https://i.giphy.com/media/3UYKM1nrL2MPAYYRzV/source.mp4

**Contexto**
Pode afetar diversos jogadores em diversos roleplays, as vezes um cara armado com um fuzil, pode vir um cara de moto e simplesmente dá um chutão e ja era.

**Solução possível**
Que tenha um dano muito menor ou que seja retirado.

**Comment by fmd00** [comment]
Desabilitado no próximo patch.
