### ISSUE TITLE
Bater algemado

### ISSUE THREAD

**Issue by R0M4NO** [Blaine-Life/blaine-issues#7]
**Versão do Servidor**

`Versão v1.2.0 alpha`

**Comportamento atual**

Tá sendo possível bater algemado.

**Comportamento esperado**

Escreva aqui...

**Passos para reprodução**

https://cdn.discordapp.com/attachments/644975249804361728/790066774523510794/unknown.png

**Contexto**

Escreva aqui...

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Corrigido na 1.3.0 alpha
