### ISSUE TITLE
Boombox não diferencia diferentes dimensões / tocam em qualquer interior com dimensões diferentes

### ISSUE THREAD

**Issue by alansiq** [Blaine-Life/blaine-issues#70]
**Versão do Servidor**

`Versão v1.5.6 Open Alpha`

**Comportamento atual**

Boombox aparentam validar apenas X,Y,Z e não a DIM do personagem - tocando em interiores de casas diferentes.

**Comportamento esperado**

Validação de DIM ou não estar disponivel dentro de interiores.

**Passos para reprodução**

Entrar em uma casa
Colocar uma boombox
Entrar em outra casa com o mesmo interior e escutar a mesma boombox

**Contexto**

Tocou um pancadão no game de todo mundo do server

**Solução possível**

valdiar dim

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.7
