### ISSUE TITLE
Remover nomes flutuantes dos itens (/config)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#71]
**Versão do Servidor**
`Versão v1.5.6 Open Alpha`

**Comportamento atual**
Atualmente os itens aparecem com o nome flutuante e a quantidade que há no local. Quando existe um acúmulo de objetos, a tela fica poluída.

**Comportamento esperado**
Acrescentar um tog no /config.

**Passos para reprodução**
https://cdn.discordapp.com/attachments/774132113636327434/799738492598616084/unknown.png

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Adicionado na 1.5.7
