### ISSUE TITLE
Demitir do LSFD não retorna mensagem correta

### ISSUE THREAD

**Issue by matheussbdo** [Blaine-Life/blaine-issues#72]
**Versão do Servidor**

`Versão v1.5.6.oa`

**Comportamento atual**

Quando quero demitir um membro do LSFD, dou o comando /rank ID -1, porém quando executo esse comando o aviso que me retorna é de que o membro no qual estou demitindo não é da minha facção, quando na verdade ele é e foi demitido.

**Comportamento esperado**

Quando o comando for executado, aparecer no chat da facção (assim como é o /f) que tal pessoa foi demitida da facção para todos on-line verem, e caso eu esteja dando esse comando aparecer algum retorno também no chat como: Você demitiu player X da facção com sucesso.

**Passos para reprodução**

—.

**Contexto**

—.

**Solução possível**

—.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.7
