### ISSUE TITLE
Celular (conversas)

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#73]
**Versão do Servidor**
`Versão v1.5.6 Open Alpha`

**Comportamento atual**
Quando você envia mensagem pra duas pessoas diferentes, ele cria duas novas conversas. Quando você vai mandar mensagem para uma terceira pessoa e criar uma terceira conversa, ao invés de ir para essa pessoa, ele envia a mensagem para o número anterior que você enviou (no caso a segunda pessoa). Somente pelo celular, no /sms ele funcionou normalmente.

**Comportamento esperado**
N/A

**Passos para reprodução**
https://www.youtube.com/watch?v=jQPvvT0FqNU

**Contexto**
N/A

**Solução possível**
N/A

**Comment by vanessa** [comment]
@manodjoes Valeu. Quando você colocar o vídeo vai ajudar.

**Comment by vanessa** [comment]
Para controle interno: https://linear.app/blainelife/issue/GM-138/terceiro-chat-quebra-app-de-mensagens

**Comment by VictorFerraresi** [comment]
O celular está sendo trocado pela versão do Closed Alpha.
