### ISSUE TITLE
/propriedades

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#75]
**Descrição curta**
Criar um /propriedades que irá constar as seguintes informações:

ID Propriedade: XXXX / Endereço: N°, Rua, Bairro / Alugada: Sim/Não / Preço: Colocar o preço original dela
ID Empresa: XXXX / Endereço: N°, Rua, Bairro / Entrada: Preço do valor de entrada / Preço: Colocar o preço original dela

**Descrição detalhada**
N/A

**Como essa sugestão vai melhorar o servidor?**
N/A

**Comment by VictorFerraresi** [comment]
Implementado
