### ISSUE TITLE
Colocar as opções para o /armazenamento

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#76]
**Descrição curta**
O comando /armazenamento não aparece as possíveis opções de utilização, como "ver, colocar, pegar". Se tiver algum novato no servidor, ele provavelmente não vai saber utilizar.

**Descrição detalhada**
Que apareça ao usar /armazenamento e não ao dar /armazenamento + alguma palavra aleatória.

**Como essa sugestão vai melhorar o servidor?**
N/A

**Comment by VictorFerraresi** [comment]
Implementado na 1.7.5
