### ISSUE TITLE
É possível derrubar uma moto dando apenas um chute

### ISSUE THREAD

**Issue by vanessa** [Blaine-Life/blaine-issues#77]
**Versão do Servidor**

`Versão v1.5.6 Open Alpha`

**Comportamento atual**

https://streamable.com/fgsmna

**Comportamento esperado**

Não ter força suficiente para derrubar uma moto com chute.

**Passos para reprodução**

1. Peça para algum amigo subir numa moto/bicicleta
2. Tente dar um soco na moto

**Contexto**

N/A

**Solução possível**

N/A

**Comment by VictorFerraresi** [comment]
Pesquisei e testei as nativas de dano e melee attack e entendemos que isso é realmente um comportamento inalterável (pelo menos sem o desenvolvimento do sistema de danos completo) do próprio GTA V.
