### ISSUE TITLE
Sugestão - Furto de veiculo (arrombamento e ligação direta!).

### ISSUE THREAD

**Issue by BelixKrux** [Blaine-Life/blaine-issues#78]
**Descrição curta**

Um modelo/ideia pra ligação direta, furtos de veículos e o uso das travas de segurança, seguros e adições extras em veículos.

**Descrição detalhada**

**Modos diferentes para abrir a porta e ligar o carro!**

Primeiramente um carro que saiu da concessionária:
- Para abrir o ladrão tem 2 possibilidades 
  1ª Abrindo o carro com uma ferramenta, demora cerca de 3 minutos até que a trava quebre, o alarme não dispara.  
  A 2ª possibilidade é quebrando o vidro com um comando, demora 5 segundos, tempo de fazer algum tipo de animação e o vidro se quebrar, tempo pra impedir a ação de acontecer, apenas andando ou algum comando como /stop, exigir a confirmação antes de iniciar a ação, pra impedir que o comando seja feito "sem querer".

- Após já estar dentro do veiculo tem as opções de ligação direta, como no jogo _among us_, algo parecido com isso 
  [(click aqui para ver a imagem).](https://i1.wp.com/paradoxalnews.com/wp-content/uploads/2020/11/Among-Us-novas-tasks-Don_Pasquale-Reddit.jpg?resize=780%2C726&ssl=1) O player teria que acertar quais os fios e haveria 30% de chance de funcionar mesmo com os fios certos, porém os certos sairiam uma faísca, os fios seriam definidos por concessionária e upgrade, exemplo: Concessionária de motos, tem 3 fios, se juntar o amarelo com o vermelho o carro liga, porém só tem 30% de chance do carro ligar, então teria que ficar batendo os fios até o carro ligar.

Agora um carro que já tem o máximo de upgrades, seguro, travas, ~robo armado dentro do carro, zuera~:

- Pra abrir o carro não seria tão simples como usar uma chave de fenda, teria que comprar um aparelho de decodificação (que seria tão difícil achar como arma pra vender) OU usando a chave de fenda ou quebrando o vidro, porém o alarme de segurança além de ser acionado caso a tentativa fosse essas outras escolhas, de maneira escandalosa, ele, automaticamente avisaria para o dono e ainda avisaria também pra policia que um furto em um veiculo X está acontecendo no lugar X.

- Depois que estivesse dentro do veiculo, teria que remover uma trava de segurança, isso poderia ser algum outro minigame escolhido pela equipe, algo que fizesse a pessoa ter que refazer o minigame umas 10 vezes, então finalmente após remover a trava, desparafusa o painel pra ver os fios, em 5 segundos os fios aparecem, como o do _among us_ que citei acima, então teriam entre 15 a 20 fios (dependendo da concessionária, modelo e upgrade) de cores diferentes e apenas 2 fios juntos, de cores separadas conseguiria ligar o carro, mesmo assim só com 5% de acerto mesmo sendo usado o fio certo, a diferença é que iria criar uma espécie de faísca caso o fio fosse o certo, porém além disso, haveria um outro conjunto de fios com 100% de acerto, o alarme dispararia se fosse acionado.

**Como essa sugestão vai melhorar o servidor?**

Bom, roleplay de roubo de carro é um tipo de roleplay necessário por todos os tipos de players criminosos, nem sempre com o mesmo objetivo, alguns pra vender peças, fazer rp de desmanche, outros pra clonagem, alguns usam pra fazer outros crimes como assaltos, além de dar mais trabalho para a policia, sempre vai ter uma ligação chegando pra eles "Roubaram meu carro, subaru azul"

Gostaria de apenas acrescentar, isso é uma ideia, se ler com a mente aberta pode retirar ideias dessas ideias e ter novas ideias melhores que as ideias das ideias originariamente das ideias.

**Comment by VictorFerraresi** [comment]
Sistema de lockpicking e hotwiring implementado na 1.8.0oa
