### ISSUE TITLE
/mecanico e /cancelarmecanico não existe

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#8]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

O comando /mecanico e o /cancelarmecanico que serviriam para chamar e cancelar um mecânico não volta nenhuma mensagem de "Não existem mecânicos em trabalho", na verdade ele não volta nada. Ele não existe.

**Comportamento esperado**

Deveria existir

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790069114378911754/unknown.png](url)

**Contexto**

**Solução possível**

**Comment by VictorFerraresi** [comment]
O emprego de mecânico ainda não foi implementado.
