### ISSUE TITLE
Animação em motos

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#80]
**Versão do Servidor**
`Versão v1.5.7`

**Comportamento atual**
Ao realizar qualquer animação como piloto ou passageiro de uma moto, você é automaticamente ejetado, parado ou em movimento.

**Comportamento esperado**
N/A

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.8
