### ISSUE TITLE
Cigarros / Bebidas alcoólicas são enchidas ao relogar

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#81]
**Versão do Servidor**
`Versão v1.5.7`

**Comportamento atual**
Ao consumir um cigarro ou alguns ml de uma bebida alcoólica e depois disso relogar, ambos voltam cheios. Não tenho 100% de certeza sobre a bebida alcoólica, já que eu não testei agora, mas dá última vez que eu tinha visto, encheu.

**Comportamento esperado**
N/A

**Passos para reprodução**
Antes de relogar: https://u.cubeupload.com/tiomarcelo/Screenshot1.png
Depois de relogar: https://u.cubeupload.com/tiomarcelo/13eScreenshot2.png

**Contexto**
N/A

**Solução possível**
N/A

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.9oa.

**Comment by VictorFerraresi** [comment]
Aparentemente o problema persiste

**Comment by VictorFerraresi** [comment]
Corrigido na 1.7.2
