### ISSUE TITLE
/v ferrovelho dando pra vender o veículo em qualquer lugar.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#82]
**Versão do Servidor**

`Versão v1.2.35 alpha`

**Comportamento atual**
Está dando para vender qualquer veículo em qualquer lugar do mapa.

**Comportamento esperado**
Que de pra vender apenas no ferro velho e que tenha um ícone no mapa escrito "Ferro-Velho", para os jogadores se localizarem.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
Que de pra vender apenas no ferro velho e que tenha um ícone no mapa escrito "Ferro-Velho", para os jogadores se localizarem.

**Comment by VictorFerraresi** [comment]
É comportamento esperado
