### ISSUE TITLE
Mostrar nametag se for conhecido

### ISSUE THREAD

**Issue by adrielcasser** [Blaine-Life/blaine-issues#83]
**Descrição curta**
Players que você conheça exibirão o nome em cima da cabeça, e outros que você não conheça teria um ID ou N° de matricula do personagem sobre ele.

**Descrição detalhada**
Pessoas que você conheça exibirão o nome em cima da cabeça caso não estejam com o rosto coberto por algum acessório como máscara por exemplo, e pessoas que você não conheça terão um [ID] sobre a cabeça, como se fosse uma lista de contatos mental, assim como você vê alguém na rua e reconhece com um nome ou apelido, assim será no jogo,  caso você não conheça a pessoa pra você é só mais um desconhecido com um número aleatório de identificação no seu subconsciente.
**Como essa sugestão vai melhorar o servidor?**
Seria baseado na vida real, deixando um RP mais realista.

**Comment by VictorFerraresi** [comment]
Essa sugestão já foi discutida previamente, inclusive em outros servidores, e por diversos motivos não é factível.
