### ISSUE TITLE
[BUG] Celular Congelando

### ISSUE THREAD

**Issue by SeHisoka** [Blaine-Life/blaine-issues#86]
**Versão do Servidor**

`Versão v1.5.8 Open Alpha`

**Comportamento atual**

Atualmente com a atualização do sistema de celular, ele está congelando os jogadores em qualquer ação após a primeira aparição do celular na sua tela. Ele congela o personagem de todas suas ações.

**Comportamento esperado**

Usar o personagem livremente enquanto ainda usa o celular, conseguindo andar ou algo do gênero.

**Passos para reprodução**

O estado cenário mais crítico possível é alguém dirigindo um carro: Dirija seu carro normalmente e acelere, não pare. Peça para algum outro jogador ligar para você enquanto dirige. Logo após o celular aparecer na sua tela, você ficará congelado até atender o celular ou sair daquela freeze de alguma maneira saindo da ala do celular.

**Contexto**

Infelizmente causei um acidente IC porque me ligaram enquanto eu conduzia um veiculo e, sem saber inicialmente o problema, acabei atropelando duas pessoas pois o carro "perdeu a direção" comigo congelado, sequer freava.

**Solução possível**

Retirar esse congelamento do personagem enquanto usa o celular.

**Comment by vanessa** [comment]
Obrigada por reportar. Estamos cientes do bug e vamos resolvê-lo @SeHisoka

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.9, a ligação recebida não travará mais o seu jogo no susto.

Sobre os outros travamentos (ex: abrir com a setinha pra cima) é só apertar F1 pra esconder o cursor e liberar o controle!
