### ISSUE TITLE
/aestacionar não funciona

### ISSUE THREAD

**Issue by Maict** [Blaine-Life/blaine-issues#9]
**Versão do Servidor**

`Versão v1.2.0 Alpha`

**Comportamento atual**

/aestacionar não funciona. Primeiro eu tentei usar o comando /aestacionar com veiculos que são spawnados por admin /veh model bla bla, mas não deu. De começo achei que fosse pelo fato do veiculo não ter dono e então fui na concessionária comprar um carro para testar mais uma vez, e para nenhuma surpresa minha eu vi que não estacionou nem um carro cujo existe dono. Portando, o /aestacionar não está funcionando

**Comportamento esperado**

Deveria sei lá, sumir com o carro

**Passos para reprodução**

[https://cdn.discordapp.com/attachments/644975249804361728/790070996405190686/unknown.png](url)

**Contexto**

Escreva aqui...

**Solução possível**

Escreva aqui...

**Comment by VictorFerraresi** [comment]
Não é um bug, o /aestacionar é responsável apenas por editar a posição de spawn do veículo. Você provavelmente alterou a posição do seu /v estacionar.

Você pode utilizar esse comando também para alterar a posição que veículos de emprego spawnam.
