### ISSUE TITLE
A cada interior que você entra, o personagem faz uma ultima animação realizada.

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#91]
**Versão do Servidor**

`Versão v1.5.8 Open Alpha`

**Comportamento atual**
Se você deu por exemplo /lean 1 em algum momento de algum RP, e aí você vai e entrar em algum interior, o seu personagem entra dentro do interior utilizando o /lean 1

**Comportamento esperado**
Era pro personagem entrar no interior e ficar sem animação nenhuma.

**Passos para reprodução**
https://imgur.com/nYOxZEH

**Contexto**
N/A

**Solução possível**
Que não faça nenhuma animação ao entrar em interiores.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.5.9
