### ISSUE TITLE
Render de itens no chão não checa dim - Validar dim /dropar (ou /dropare)

### ISSUE THREAD

**Issue by alansiq** [Blaine-Life/blaine-issues#92]
**Versão do Servidor**

`Versão v1.5.6 Open Alpha`

**Comportamento atual**

Itens no chão aparentam validar apenas X,Y,Z - fazendo com que drop de items em interiores idênticos sejam compartilhados entre diferentes residências.

(Mesmo X,Y,Z porém DIM da propriedade)

**Comportamento esperado**

Carregar items válidos para a dim atual do jogador.

**Passos para reprodução**

 /irinterior (escolher qualquer um da lista)
/dropar qualquer item do seu inventário
/dim seu_id dim_aleatória
Ver que o item continua dropado, mesmo em outra propriedade.

**Contexto**

Bug identificado pelo usuário NoWay no Discord e válidado por Alligator

**Solução possível**

1. Proibir drop de items em interiores (não recomendado)
2. Validar DIM antes de carregar items no chão.

**De forma preventiva, recomendo bloquear o uso de /br da LSPD/SASD dentro
de interiores (dim != 0) ou já realizar a mesma verificação para o bug acima**

**Comment by fmd00** [comment]
Corrigido no próximo patch.
