### ISSUE TITLE
Galão de combustível

### ISSUE THREAD

**Issue by manodjoes** [Blaine-Life/blaine-issues#93]
**Versão do Servidor**
`Versão v1.5.8`

**Comportamento atual**
O galão de combustível que é comprovável na 24/7 não tem utilidade.

**Comportamento esperado**
Criar a possibilidade de abastecer uns 10-15% de combustível caso ele fosse comprado. Com isso, também abaixar o valor dele, já que ele custa 250$ e é praticamente isso que você gasta para encher um tanque de 0-100.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
N/A

**Comment by fmd00** [comment]
Corrigido no próximo patch.
