### ISSUE TITLE
Cabelo dos ped's não está salvando

### ISSUE THREAD

**Issue by Bubbaldinho** [Blaine-Life/blaine-issues#94]
**Versão do Servidor**
`Versão v1.5.9 Open Alpha`

**Comportamento atual**
A cada vez que você reloga, o cabelo do seu ped volta ao original da skin, dando um conflito pra quem gosta de utilizar chapéus na skin e o cabelo do ped fica visível.

**Comportamento esperado**
Que o cabelo salve.

**Passos para reprodução**
N/A

**Contexto**
N/A

**Solução possível**
Que o cabelo mudado, salve

**Comment by VictorFerraresi** [comment]
Não foi possível reproduzir o bug (nem pelo issuer do Ticket).
