### ISSUE TITLE
/ame não envia completo

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#96]
**Versão do Servidor**
`Versão v1.5.9`

**Comportamento atual**

O que você escreve no /ame não aparece completamente, é cortado pela metade se vc atinge o limite de caracteres.

**Comportamento esperado**

Aparecer inteiro.

**Passos para reprodução**

Escrever qualquer /ame grande mesmo não sendo tão grande.
Print: https://i.imgur.com/VUjI3pf.png

**Contexto**

A gente tava fazendo roleplay de pichar e o /ame do amigo não foi completo, ele teve que mandar 2x para terminar.

**Solução possível**

Aumentar o limite de caracteres num /ame.

**Comment by VictorFerraresi** [comment]
Isso se deve a uma limitação do GTA V, que permite que os textos dinâmicos escritos na tela não possuam mais de 90 caracteres.
É fácil bypassar essa limitação ao escrever textos 2D numa posição fixa da tela, mas quando precisamos converter uma coordenada 3D pra 2D (WorldToScreen), os textos se sobrepõem caso sejam criados por duas chamadas à nativa.

Ref.: https://www.youtube.com/watch?v=pd4O1-7o3dc
