### ISSUE TITLE
Portas não diferenciam por altura

### ISSUE THREAD

**Issue by cybernitsche** [Blaine-Life/blaine-issues#97]
**Versão do Servidor**

`Versão v1.5.9 Open Alpha`

**Comportamento atual**
Quando você tenta dá o comando /entrar no piso debaixo, entra na casa que tá em cima.

**Comportamento esperado**
Que só pudesse entrar naquela porta no piso em que ela estivesse.

**Passos para reprodução**
Basta chegar em um lugar onde tenha a porta da casa em um lugar que tu pode entrar por baixo, depois disso é só ficar embaixo da porta e dar /entrar.
vídeo: https://www.youtube.com/watch?v=YaCC3MVdiyI

**Contexto**
Fui sair da moto que estaciono embaixo da porta da casa de outra pessoa e confundi a keybind Y (desligar) com K (entrar), e acabei entrando na casa de uma pessoa nada a ver. Pessoas podem abusar disso pra fugir durante uma perseguição ou acabar entrando na casa de uma pessoa que nem conhece por acidente.

**Solução possível**
Diminuir o range do /entrar de acordo com altura.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.0
