### ISSUE TITLE
Tatuagens de outro personagem aparece na criação de um novo personagem

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#98]
**Versão do Servidor**
`Versão v1.5.9`

**Comportamento atual**

As tatuagens que vc tem em outro personagem aparecem quando vc vai criar um novo personagem, elas ficam ali até o momento da criação, quando vc spawna ela desaparecesse.
Print: https://i.imgur.com/uiwZFm3.png

**Comportamento esperado**

As tatuagens não deviam aparecer já que o personagem é novo.

**Passos para reprodução**

1 - Pega um personagem e coloca tatuagem nele.
2 - Desconecte do servidor e crie um novo personagem, na hora de customizar as tatuagens que vc escolheu vão aparecer no novo personagem mas será só visualmente, quando spawnar elas somem.

**Contexto**

Eu achei que tava bugado, em que as tatuagens iriam ficar nesse personagem tbm mas só serviu pra me enganar msm kkkkk

**Solução possível**

N/A.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.1
