### ISSUE TITLE
Se alguém ligar para a pessoa no banco do passageiro o carro bate numa parede invisivel.

### ISSUE THREAD

**Issue by sentinel5959** [Blaine-Life/blaine-issues#99]
**Versão do Servidor**

`Versão v1.5.7.`

**Comportamento atual**

Alguém ligou pro meu amigo no banco do passageiro 2 vezes enquanto eu estava dirigindo e o carro travou, como se tivesse batido numa parede invisivel ou passado por uma lombada invisivel.

**Comportamento esperado**

O carro continuar indo de boa.

**Passos para reprodução**

Assume a direção de um Bobcat e peça para alguém ligar para seu amigo no banco do passageiro.
Video: https://youtu.be/sqDBI4I9Kq8

**Contexto**

Não chegou a quebrar o carro, não me atrapalhou mas é um bug chato. 

**Solução possível**

N/A.

**Comment by VictorFerraresi** [comment]
Corrigido na 1.6.1
